<div class="panel panel-info" id="divEditPDF">
        <div class="panel-heading">
            <center><h3>¿Desea eliminar al usuario: <?php echo Session::get('sess_nom_us')?>?</h3></center> 
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-12">
                   
     
                    <center><input type="button" class="finish btn-primary btn" id="btnBorrarUsuario" style='background-color:#f29797;' o value="Eliminar Usuario" onclick="abreEliminarUser('<?php echo BASE_URL; ?>sistema/borrarUsuarios', 'Eliminar Usuario', '<?php Session::get('sess_EU_codUs') ?>')"/></center>
    
                    
                </div>
            </div>
        </div>
    </div>
<script>
    function abreEliminarUser(docPHP, titulo, cod)
{
    $("#ML_divPopup").html('');
    $("#ML_tituloForm").html(titulo);
    $.post(docPHP, 
    {
        post_open: 'on',
        post_codUs: cod
    }, function(data)
    {
        $("#ML_divPopup").html('<div class="alert alert-dismissable alert-success"><strong>Terminado</strong><br/><img src="<?php echo $_layoutParams['ruta_img'];?>ok.png" width="32" border="0" /> Proceso realizado con &eacute;xito.</div>');
        setTimeout("location.href = '<?php echo BASE_URL;?>sistema/usuarios'", 2000);
    });
}
</script>
