

   
        <div class="panel-heading">
            <center><h3>Reserva</h3></center>

        </div>
        <div class="panel-body" >
            <div class="row">
                <div class="col-md-12" id="BK_div">  
                            <div class="col-sm-9" style="width: 100%; font-size: 12px;">
                                <table style="font-size: 12px;">

                                    <tbody>
                                        <tr>
                                            <td>
                                                <div style="width: 250px; height: 115px">
                                                    <img id="imgLogo" width="250" height="115" src="<?php echo BASE_URL . ENT_LOGO; ?>">
                                                </div>
                                
                                            </td>
                                            
                                            
                                        </tr>                                       
                                    </table>
                               
                                <table style="font-size: 12px; margin-top: 20px;">
                                        <tr>
                                            <th width="35%">Cliente:</th>
                                            <td>
                                                
                                            </td>
                                            <th width="5%"></th>
                                            <th width="35%">  Usuario:</th>
                                            <td>
                                              
                                            </td>
                                            <th></th>
                                            
                                        </tr>
                                        <tr>

                                            <th>Pasajero:</th>
                                            <td></td>
                                            <th width="5%"></th>
                                            <th>Fecha In:</th>
                                            <td></td>
                                        </tr>
                                        

                                    </tbody>
                                </table>
                                <div class="panel-heading">
                                        <center><h3>Detalle Servicios</h3></center>
                                    </div>
                                
                                        <div class="table-responsive">
                                             
                                              <table class="table table-bordered table-striped"  style="font-size: 11px;" >
                                                               
                                                               <?php 
                                                               if($this->objCarro)
                                                               {
                                                                   ?>
                                                                   <thead>
                                                                    <tr>
                                                                        <th width="70">Status</th>
                                                                        <th>Servicio</th>
                                                                        <th>Habitaci&oacute;n</th>
                                                                        <th>P.A.</th>
                                                                        <th>N&deg; hab.</th>
                                                                        <th>A.</th>
                                                                        <th>C.</th>
                                                                        <th>Pais</th>
                                                                        <th>Ciudad</th>
                                                                        <th>Fecha In</th>
                                                                        <th>Fecha Out</th>
                                                                        <th>Vuelo</th>
                                                                        <th>Total</th>
                                                                        <th></th>
                                                                    </tr>
                                                                </thead>
                                                                  <?php
                                                                   $totalCompras=0;
                                                                   foreach($this->objCarro as $objCar )
                                                                   {
                                                               ?>   
                                                                
                                                                        <tbody>
                                                                            <tr>
                                                                                <th><span class="label label-success"><?php echo $objCar->getStatus(); ?></span></th>
                                                                                <td><?php echo $objCar->getServicio(); ?></td>
                                                                                <td class="text-muted"><?php echo $objCar->getHabitacion() ?></td>
                                                                                <td><?php echo $objCar->getPa() ?></td>
                                                                                <td><?php echo $objCar->getNhab() ?></td>
                                                                                <td><?php echo $objCar->getA() ?></td>
                                                                                <td class="text-muted"><?php echo $objCar->getC() ?></td>
                                                                                <td><?php  echo $objCar->getPais() ?></td>
                                                                                <td><?php echo $objCar->getCiudad() ?></td>
                                                                                <td><?php echo Funciones::invertirFecha($objCar->getFecha_in(), '-', '/') ?></td>
                                                                                <td class="text-muted"><?php if($objCar->getFecha_out()=='0000-00-00'){echo "";} else {echo Funciones::invertirFecha($objCar->getFecha_out(),'-','/');} ?></td>
                                                                                <td><?php echo $objCar->getVuelo() ?></td>
                                                                                <td style="color: #DF5F00; font-weight: bold;"><?php echo $objCar->getTotal() ?></td>                                                                               
                                                                                <td></td>
                                                                            </tr>
                                                                            
                                                                
                                                                <?php
                                                                   }
                                                                   ?>
                                                                            <tr>
                                                                                <td colspan="12" align="right">Total</td>
                                                                                <td style="color: #DF5F00; font-weight: bold;"><?php echo $totalCompras+=$objCar->getTotal()?></td>
                                                                                <td></td>
                                                                            </tr>
                                                                        </tbody>
                                                                        
          
                                                                 <?php
                                                               }
                                                               else{
                                                                ?>  
                                                                        <tr>
                                                                            <td>
                                                                        <center><strong>No se encontraron reservas.</strong></center>
                                                                            </td>
                                                                        </tr>
                                                                        <table>                                                            </table>
                                                            
                                    

                                                                <?php   
                                                               }
                           
                                                                ?>
                                                   
                                                     </div>

                                <div class="panel-heading">
                                    <center><h3>Detalle Pasajeros</h3></center>
                                    

                                </div>
                                <table class="table table-condensed" style="font-size:12px;">
                               
                                            <?php
                                                    if(Session::get('sess_pBP_cntHab')){
                                                    for($i = 1; $i<=Session::get('sess_pBP_cntHab'); $i++){
                                             ?>
                                                        <thead>
                                                        <tr>
                                                            <th width="100">Habitaci&oacute;n <?php echo $i ?></th>
                                                            <th>Nombres</th>
                                                            <th>Apellidos</th>
                                                        </tr>
                                                       </thead>
                                                        <?php
                                                        for($j=1; $j<=$this->carrAdlNombre; $j++){
                                                        ?>
                                                                    <tr>
                                                                      <th>Adulto <?php echo $j;?></th>
                                                                      <td>Nombre</td>                             
                                                                      <td><?php echo $this->carrAdlNombre[$j]; ?></td> 
                                                                   <?php
                                                        }
                                                        for($k=1; $k<=$this->carrAdlApellido; $k++){
                                                                   ?>
                                                                      <td>Apellido</td> 
                                                                      <td><?php $this->carrAdlApellido[$k];?></td> 
                                                                      <td></td> 
                                                                    </tr>                       
                                                     <?php
                                                        }
                                                        } 
                                                    }
                                                    //Session::destroy('sess_BP_Adl_1');
                                                    //Session::destroy('sess_BP_Adl_2');
                                                    //Session::destroy('sess_BP_Adl_3');
                                                    //Session::destroy('sess_BP_Adl_4');
                                               ?>
                                                                    
                                                                    <div>
                                                                        
                                                                    </div>
             
                                </table>
                                
                                
                            </div>
                                 
                    </div>
                 
            </div>
        </div>
              
    <span class="pull-right">
        <input type="button" class="finish btn-default btn" id="btnAtr_P3" value="Atras" />
        <input type="submit" class="finish btn-success btn" value="Reservar" />
    </span>
    <br>
                                        