 <form enctype="multipart/form-data" class="frmEditPDF">

    <div class="panel panel-info" id="divEditPDF">
        <div class="panel-heading">
            <h4><b>Programa:</b> <?php echo $this->SP_codProg; ?></h4>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-12">
                    <table align="center">
                        <tr>
                            <td width="450">
                                <div class="col-sm-9">
                                    <div class="fileinput fileinput-new" data-provides="fileinput">

                                       <?php
                                        $texto_cambiado = str_replace(" ", "_",$this->SP_codProg);  
                                           $nomArchivo = ROOT. DS .'public'. DS .'pdf'. DS .'upl_'.$texto_cambiado.'.pdf';
                                           
                                           if (file_exists($nomArchivo)) 
                                           {  
                                           ?>
                                        <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 150px; padding-top:10px;">
                                            
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>pdf_gran.png" />
                                            
                                            <input id="txtNombreFile" name="txtNombreFile" type="hidden" value="<?php echo 'upl_'.$texto_cambiado.'.pdf'; ?>"/>
                                        </div>
                                        <center>
                                            <label style="cursor:pointer; display: none;">
                                                <input style="margin-top:-1px; vertical-align:middle;" type="checkbox" name="chkEP_flPDF" checked="checked"> Eliminar
                                            </label>
                                            <input type="button"  id="btnEP_CargaPDF" class="btn btn-primary" value="Eliminar" 
                                            onclick="procesoEnviaForm('frmEditPDF', '<?php echo BASE_URL ?>sistema/eliminarPdf', 'btnEP_CargaPDF', 'divEditPDF')">
                                        </center>
                                         <?php
                                           }
                                           
                                           else{
                                          ?>
                                        

                                        <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 150px;"></div>
                                        <div>
                                            <span class="btn btn-default btn-file">
                                                <span class="fileinput-new">Seleccionar</span>
                                                <span class="fileinput-exists">Cambiar</span>
                                                <input type="file" name="SpFile" id="SpFile" accept="application/pdf"/>
                                            </span>
                                            <input type="hidden" id="txtFile" name="txtFile" value="<?php echo $this->SP_codProg;?>"/>
                                            <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remover</a>
                                            <input type="button"  id="btnEP_CargaPDF" class="btn btn-primary" value="Subir PDF" 
                                            onclick="procesoEnviaForm('frmEditPDF', '<?php echo BASE_URL ?>sistema/subirCarPdf', 'btnEP_CargaPDF', 'divEditPDF')">
                                        </div>

                                       <?php
                                       
                                           }
                                       ?>

                                    </div>
                                </div>
                            </td>
                        </tr>
                     </table>
                </div>
            </div>
        </div>
    </div>

</form> 

 <script>
    function procesoEnviaForm(classFrm,url){
    
        initLoad();
      var formData = new FormData($("." + classFrm)[0]);
     
        $.ajax({
             type:"POST", 
             url:url,
             data:formData,
             cache: false,
             contentType: false,
             processData: false,
             beforeSend: function () {
             },
             success:function(data)
             {  
                 //alert(data);
                 endLoad();
                 if(data != 'OK'){
                    $("#msjWar").html(data);
                    noExito();
                 }
                 else{
                    
                    $("#ML_divPopup").html('<div class="alert alert-dismissable alert-success"><strong>Terminado</strong><br/><img src="<?php echo $_layoutParams['ruta_img'];?>ok.png" width="32" border="0" /> Proceso realizado con &eacute;xito.</div>'); 
                   //exito();
                    setTimeout("location.href = '<?php echo BASE_URL;?>sistema/adminProgramas'", 2000);
                    
                 }
             }
             
             
             
         });
         return false;
    
        
     
        
        
    } 
    
    </script>