
        <div class="panel-heading">
            <center><h3>Reserva</h3></center>

        </div>
        <div class="panel-body" >
            <div class="row">
                <div class="col-md-12" id="BK_div">  
                            <div class="col-sm-9" style="width: 100%; font-size: 12px;">
                                <table style="font-size: 12px;">

                                    <tbody>
                                        <tr>
                                            <td>
                                                <div style="width: 250px; height: 115px">
                                                    <img id="imgLogo" width="250" height="115" src="<?php echo BASE_URL . ENT_LOGO; ?>">
                                                </div>
                                
                                            </td>
                                            
                                            
                                        </tr>                                       
                                    </table>
                               
                                <table style="font-size: 12px; margin-top: 20px;">
                                        <tr>
                                            <th width="35%">Cliente: </th>
                                            <td>
                                             <?php echo' '.Session::get('sess_usuario'); ?>   
                                            </td>
                                            <th width="5%"></th>
                                            <th width="35%">  Usuario: </th>
                                            <td>
                                              <?php echo' '.Session::get('sess_nombre').' '.Session::get('sess_apellido'); ?>
                                            </td>
                                            <th></th>
                                            
                                        </tr>
                                        <tr>

                                            <th>Pasajero:</th>
                                            <td><?php if($this->objNombrePax & $this->objApellidoPax){ echo $this->objNombrePax.' '.$this->objApellidoPax;}?></td>
                                            <th width="5%"></th>
                                            <th>Fecha In:</th>
                                            <td><?php echo date('d/m/Y'); ?></td>
                                        </tr>
                                        

                                    </tbody>
                                </table>
                                <div class="panel-heading">
                                        <center><h3>Detalle Servicios</h3></center>
                                    </div>
                                
                                        <div class="table-responsive">
                                             
                                              <table class="table table-bordered table-striped"  style="font-size: 11px;" >
                                                               
                                                               <?php 
                                                               if($this->objCarro)
                                                               {
                                                                   ?>
                                                                   <thead>
                                                                    <tr>
                                                                        <th width="3%">Status</th>
                                                                        <th width="25%">Servicio</th>
                                                                        <th width="5%">Habitaci&oacute;n</th>
                                                                        <th width="3%">P.A.</th>
                                                                        <th width="5%">N&deg; hab.</th>
                                                                        <th width="3%">A.</th>
                                                                        <th width="3%">C.</th>
                                                                        <th width="8%">Ciudad</th>
                                                                        <th width="5%">Fecha In</th>
                                                                        <th width="5%">Fecha Out</th>
                                                                        <th width="5%">Vuelo</th>
                                                                        <th width="5%">Total</th>
                                                                        <th width="3%"></th>
                                                                        
                                                                    </tr>
                                                                </thead>
                                                                  <?php
                                                                   $totalCompras=0;
                                                                   $contProductosP3=0;
                                                                   $arrayFechas = Session::get('sess_arrayFechasCarro');
                                                                   $arrayVuelos = Session::get('sess_arrayVuelosCarro');
                                                                   foreach($this->objCarro as $objCar )
                                                                   {
                                                                       $contProductosP3++;
                                                               ?>   
                                                                
                                                                        <tbody>
                                                                            <tr>
                                                                                
                                                                                <th><span class="<?php if($objCar->getStatus() == 'AVAILABLE'){echo 'label label-success';} else{echo 'label label-warning';} ?>"><?php if($objCar->getPrograma() != '' && $objCar->getServicio()== 'HTL'){echo '';} else{ echo $objCar->getStatus(); } ?></span></th>
                                                                                <td><?php echo $objCar->getServicio(); ?></td>
                                                                                <td class="text-muted"><?php echo $objCar->getHabitacion() ?></td>
                                                                                <td><?php echo $objCar->getPa() ?></td>
                                                                                <td><?php echo $objCar->getNhab() ?></td>
                                                                                <td><?php echo $objCar->getA() ?></td>
                                                                                <td class="text-muted"><?php echo $objCar->getC() ?></td>
                                                                                <td><?php  echo $objCar->getPais() ?></td>
                                                                                <td><?php echo $objCar->getCiudad() ?></td>
                                                                                <td><?php if($arrayFechas[$contProductosP3] != null){echo $arrayFechas[$contProductosP3];} //echo Funciones::invertirFecha($objCar->getFecha_in(), '-', '/') ?></td>
                                                                                <td class="text-muted"><?php if($objCar->getFecha_out()=='0000-00-00'){echo "";} else {echo Funciones::invertirFecha($objCar->getFecha_out(),'-','/');} ?></td>
                                                                                <td><?php if($arrayVuelos[$contProductosP3]!= null){echo $arrayVuelos[$contProductosP3];} ?></td>
                                                                                <td style="color: #DF5F00; font-weight: bold;"><?php echo $objCar->getTotal() ?></td>                                                                               
                                                                                <?php $totalCompras+=$objCar->getTotal()?>
                                                                            </tr>
                                                                            
                                                                </tbody>
                                                                <?php
                                                                   }
                                                                   ?>
                                                                        
                                                                            <tr>
                                                                                
                                                                                <td colspan="11" align="right"><h5>Total</h5></td>
                                                                                <td  colspan="2" style="color: #DF5F00; font-weight: bold;"><h5><?php echo $totalCompras ?></h5></td>
                                                                                
                                                                            </tr>
                                                                        
                                                                        
          
                                                                 <?php
                                                               }
                                                               else{
                                                                ?>  
                                                                        <tr>
                                                                            <td>
                                                                        <center><strong>No se encontraron reservas.</strong></center>
                                                                            </td>
                                                                        </tr>
                                                                        <table>                                                            </table>
                                                            
                                    

                                                                <?php   
                                                               }
                           
                                                                ?>
                                                   
                                                     </div>

                                
                                <table class="table table-condensed" style="font-size:12px;"> 
                                    <div class="panel-heading">
                                    <center><h3>Detalle Pasajeros</h3></center>
                                    

                                     </div>
                                                        <?php
                                                        if($this->objPaxCarro){
                                                            $contHab=1;
                                                            $contHabAnt=0;
                                                            $contAd=0;
                                                           foreach($this->objPaxCarro as $objCarro){                                                       
                                                            //echo Session::get('sess_BP_Adl_'.$objCarro->getHabitacion());
                                                               $contHabAnt = $objCarro->getHabitacion();
                                                              if($contHab == $contHabAnt){
                                                                  
                                                               ?>
                                                                    <tr>
                                                                        <th width="100">Habitaci&oacute;n <?php echo $objCarro->getHabitacion() ?></th>
                                                                        <th>Nombres</th>
                                                                        <th>Apellidos</th>
                                                                       
                                                                    </tr>                   
                                                               <?php                                                             
                                                                $contAd=0;
                                                                $contCh=0;
                                                                $contHab++;
                                                              }
                                                             
                                                              else{
                                                              $contAd++;
                                                              $contCh++;  
                                                              }
                                                             
                                                              
                                                               if($contAd <= Session::get('sess_BP_Adl_'.$objCarro->getHabitacion())){                                                                                   
                                                                   
                                                                   ?> 
                                                                    
                                                                    <tr>
                                                                      <td>Adulto <?php echo $contAd+1; ?></td>
                                                                                                 
                                                                      <td><?php echo $objCarro->getNombre(); ?></td> 
                                                                   
                                                                      
                                                                      <td><?php echo $objCarro->getApellido();?></td> 
                                                                      <td></td> 
                                                                    </tr> 
                                                                        <?php 
                                                                        if($contCh <= Session::get('sess_BP_Chd_'.$objCarro->getHabitacion())){
                                                                            if($objCarro->getNombreCh() &&  $objCarro->getApellidoCh()){
                                                                   ?> 
                                                                    
                                                                    <tr>
                                                                      <td>Children <?php echo $contCh+1; ?></td>
                                                                                                 
                                                                      <td><?php echo $objCarro->getNombreCh(); ?></td> 
                                                                   
                                                                      
                                                                      <td><?php echo $objCarro->getApellidoCh();?></td> 
                                                                      <td></td> 
                                                                    </tr> 
                                                                        <?php
                                                                            } 
                                                               }
                                                               }
                                                               
                                                               
                                                              
                                                               
                                                               
                                                        }
                                                        

                                               ?>
                                                                    
                                                                    <div>
                                                                        
                                                                    </div>
             
                                </table>
                                
                                <table class="table table"  >
                                    <?php
                                    if($this->objTextoArea!= "")
                                                        ?>
                                    <th width="10%"></th>
                                    <th witdh="50%"></th>
                                         <tr>
                                              <td><strong>Nota: </strong> </td>                                                      
                                              <td><?php echo $this->objTextoArea; ?> </td>
                                         </tr>            
                                                        <?php
                                                        }
                                                        ?>
                                </table>
                                
                                
                            </div>
                                 
                    </div>
                 
            </div>
        </div>
              
    <span class="pull-right">
        <input type="button" class="finish btn-default btn" id="btnAtr_P3" value="Atras" />
        <input type="submit" class="finish btn-success btn" value="Reservar" />
    </span>
    <br>
 <?php
 
 ?>
    <script>
     $('#btnAtr_P3').on('click',function(){
        $('#basicwizard-head-2').removeClass('stepy-active');
        $('#basicwizard-step-2').css('display', 'none');
        
       
        
        $('#basicwizard-head-1').addClass('stepy-active');
        $('#basicwizard-step-1').css('display', 'block');
});   
     </script>
 <?php


 ?>