<div id="page-content">
	<div id='wrap'>
		<div id="page-heading">
        
			<!-- <ol class="breadcrumb">
				<li><a href="index.php">Dashboard</a></li>
				<li>UI Components</li>
				<li class="active">Tabs &amp; Accordions</li>
			</ol> -->

			<h1>Administrar Programas</h1>
			
		</div>
		
        
        <div class="container">

			

			<div class="row">
				<div class="col-md-12">
					<div class="panel panel-danger">
					  
					  
						<div class="panel panel-info">
                        <div class="panel-heading">
                            <h4>Editando Programa</h4>
                        </div>
                        <div class="panel-body">
                            <div class="row">
                            
                                <div class="col-md-12">
                                
                                    <div id="divAlertWar" class="alert alert-dismissable alert-warning" style="display:none;">
                                        <strong>Atenci&oacute;n!</strong>
                                        Debe ingresar una <b>Ciudad</b> para buscar.
                                        <button type="button" class="close" onClick="muestraOculta('divAlertWar', '2')">&times;</button>
                                    </div>
                                    <form method="post" id="frmAdmProg" action="process/procesoAdmProgramas.php">
                                    <table align="left" cellspacing="5" cellpadding="5">
                                        <tr>
 	                                       <td>Ciudad:</td>
                                           <td>
                                           		<!-- <input type="text" id="txtCiudad-AdmProg" name="txtCiudad-AdmProg" style="width:200px" placeholder="Ingrese ciudad de destino" onkeyup="buscarCiudad(this.value, 'frmAdmProg', 'spnCiudad-prog', 'txtCiudad-AdmProg');" autocomplete="off">
                                                        <span id="spnCiudad-prog" class="twitter-typeahead" style="position: relative; display: none; direction: ltr;"></span> -->
                                                <select name="aP_txtCiudadDestino_P" id="aP_txtCiudadDestino_P" class="form-control" >
                                                <option value="0">Seleccione destino</option>
                                                    <?php
                                                    if($this->getCiudadesPRG!=FALSE)
                                                    { 
                                                        foreach($this->getCiudadesPRG as $columCiudadesPRG)
                                                        {
                                                            $aP_codigoCiuPRG= trim($columCiudadesPRG['codigo_ciudad']);
                                                            $aP_nombreCiuPRG= trim($columCiudadesPRG['nombre_ciudad']);
                                                            $aP_nombreCiudadPRG = $aP_nombreCiuPRG." (".$aP_codigoCiuPRG.")";

                                                            if(Session::get('sess_pC_aP_ciudad')==$aP_nombreCiuPRG)
                                                            {
                                                            ?>
                                                                <option value="<?php echo $aP_nombreCiuPRG; ?>" selected="selected"><?php echo $aP_nombreCiudadPRG; ?></option>
                                                            <?php
                                                            }
                                                            else
                                                            {
                                                            ?>
                                                                <option value="<?php echo $aP_nombreCiuPRG; ?>"><?php echo $aP_nombreCiudadPRG; ?></option>
                                                            <?php
                                                            }
                                                        }
                                                    }
                                                    ?>
                                                </select>
                                           </td>
                                           <td>&nbsp;&nbsp;&nbsp;
                                                <input type="button"  id="btnAdmProg" class="btn btn-primary" value="Buscar programa">
                                                <img id="imgLoading" src="iconos/loading.gif" style="display:none" width="32" border="0" />
                                           </td>
                                        </tr>
                                    </table>
                                    </form>
                                    
                                </div>
                                
                            </div>
                        </div>
                    </div>	
								
								
								

					  
					</div>
                    
                    
                    <?php
                    if(isset($_SESSION["sess_pAP_ciudad"]))
					{
					?>
                     <script>				
					$('#btnAdmProg').delay( 10 ).fadeOut( 10 );
					$('#btnAdmProg').animate({
										'display': 'none'
									}); 
					$('#imgLoading').fadeIn( 100 );
					$('#imgLoading').animate({
										'display': 'block'
									});
					</script>
                    
                     <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                    <h4 class="modal-title" id="tituloForm">Cargar PDF</h4>
                                </div>
                                
                                <div class="modal-body" id="AP_divPopup"></div>
                                
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                                    <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
                                </div>
                            </div><!-- /.modal-content -->
                        </div><!-- /.modal-dialog -->
                    </div><!-- /.modal -->
                    
                    
                    <div class="panel panel-sky" id="contenedorBusqueda" style="display:none">
                        <div class="panel-heading">
                            <h4>Resultado de la busqueda</h4>
                        </div>
                        <div class="panel-body collapse in">
                            <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered datatables" id="example">
                                <thead>
                                    <tr style="background-color:#76c4ed;">
                                        <th>Codigo</th>
                                        <th>Nombre</th>
                                        <th>Ciudad</th>
                                        <th width="100"></th>
                                    </tr>
                                </thead>
                                <tbody>
                                	
                                    <?php
									//echo $_SESSION["sess_pAP_ciudad"];
                                    $var_getProgAdmin=false; // $privateFunctions->getProgramasAdmin($_SESSION["sess_pAP_ciudad"]);
									if($var_getProgAdmin!=FALSE)
									{ 
										foreach($var_getProgAdmin as $columProgAdm)
										{
											$aP_codigoProg= mb_convert_encoding(trim($columProgAdm['codigo']), "UTF-8", "ISO-8859-1");
											$aP_nombreProg= mb_convert_encoding(trim($columProgAdm['nombre']), "UTF-8", "ISO-8859-1");
											$aP_ciudadProg= mb_convert_encoding(trim($columProgAdm['nombreC']), "UTF-8", "ISO-8859-1");
											
											$aP_documento= trim($columProgAdm['ruta_pdf']);
											
											if(strpos($aP_documento, '.pdf') !== FALSE)
											{
												$aP_icono='pdf';
											}
											else
											{
												$aP_icono='word';
											}
									?>
                                       <tr class="odd gradeX">
                                           <td><?php echo $aP_codigoProg; ?></td>
                                           <td><?php echo $aP_nombreProg; ?></td>
                                           <td><?php echo $aP_ciudadProg; ?></td>
                                           <td align="center">
                                           <a data-toggle="modal" href="#myModal" onClick="abrePopup('editProgramas.php', '<?php echo $aP_codigoProg; ?>');">
                                           <img src="iconos/conf.png" width="24" />
                                           </a>
                                           </td>
                                       </tr>
                                   <?php }
									}
								   ?>
                                   
                                </tbody>
                            </table>
                        </div>
                    </div>
                    
                    
                    
                    <script>
					$('#btnAdmProg').fadeIn( 100 );
					$('#btnAdmProg').animate({
										'display': 'block'
									});
									
					$('#imgLoading').delay( 10 ).fadeOut( 10 );
					$('#imgLoading').animate({
										'display': 'none'
									});
					
					$('#contenedorBusqueda').fadeIn( 2000 );
					$('#contenedorBusqueda').animate({
										'display': 'block'
									});
					
					</script>
                    <?php }else{ echo '<br><br><br><br><br><br><br><br><br>'; } ?>
				</div>
			</div>
            
            


			

		</div> <!-- container -->
	</div> <!--wrap -->
</div> <!-- page-content -->