<div id="page-content">
    <div id='wrap'>
        <div id="page-heading">
            <h2 style="margin: 10px;">Hoteles en SANTIAGO/CHILE</h2>
        </div>
		
        
        <div class="container">
            <div class="row">
                
                <div class="panel panel-primary">
                    <div class="panel-heading" >
                        
                            <img src="<?php echo $_layoutParams['ruta_img']; ?>star_on.png" style="width: 20px; margin-top: -5px;">
                            <img src="<?php echo $_layoutParams['ruta_img']; ?>star_on.png" style="width: 20px; margin-top: -5px;">
                            <img src="<?php echo $_layoutParams['ruta_img']; ?>star_on.png" style="width: 20px; margin-top: -5px;">
                            <img src="<?php echo $_layoutParams['ruta_img']; ?>star_on.png" style="width: 20px; margin-top: -5px;">
                            <img src="<?php echo $_layoutParams['ruta_img']; ?>star_on.png" style=" width: 20px; margin-top: -5px;">
                             - NERUDA EXPRESS
                        
                        <div class="options">
                          <ul class="nav nav-tabs">
                            <li class="active">
                              <a href="#home1" data-toggle="tab">Tarifas</a>
                            </li>
                            <li>
                                <a href="#profile1" data-toggle="tab">Ficha T&eacute;cnica</a>
                            </li>
                            <li>
                              <a href="#messages1" data-toggle="tab">Mapa</a>
                            </li>
                          </ul>
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="tab-content">
                            <div class="tab-pane active" id="home1" >
                                <div>
                                    
                                    <table width="100%"  style="margin-top: -15px; margin-left: -15px;">
                                        <tr>
                                            <td rowspan="2" width="210" valign="top">
                                                <img src="<?php echo $_layoutParams['ruta_hoteles']; ?>1.jpg" width="200" class="img-thumbnail" style="margin-right: 10px;">
                                            </td>
                                            <td>
                                                <P style="font-size:11px"><b style="color:#FF9900;">DIRECCI&Oacute;N:</b> AV. PEDRO DE VALDIVIA 150, PROVIDENCIA</P>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td valign="top">
                                                <!-- <hr> -->
                                                <table cellpadding="0" cellspacing="0" border="0" class="table table-striped" style="width: 72%; margin-left: 58px; margin-top: 10px; font-size:12px"> <!-- class="table table-striped table-bordered" -->
                                                    <tr>
                                                        <tr>
                                                            <th role="columnheader" style="padding-left: 2px;">Tipo Habitaci&oacute;n</th>
                                                            <th role="columnheader" style="padding-left: 2px;">Plan alimenticio</th>
                                                            <th role="columnheader" style="padding-left: 2px;">Precio estadia</th>
                                                            <th role="columnheader" style="padding-left: 2px;">Status</th>
                                                        </tr>
                                                    </tr>
                                                    <tr>
                                                        <td style="padding: 2px; vertical-align: middle;">STANDARD</td>
                                                        <td style="padding: 2px; vertical-align: middle;">D.BUFFET</td>
                                                        <td style="color: #DF5F00; font-weight: bold; padding: 2px; vertical-align: middle;">USD 228,70</td>
                                                        <td style="padding: 2px; vertical-align: middle;">
                                                            <a href="#" class="btn btn-success btn-sm" style="width: 88px;">AVAILABLE</a>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td style="padding: 2px; vertical-align: middle;">SUPERIOR</td>
                                                        <td style="padding: 2px; vertical-align: middle;">D.BUFFET</td>
                                                        <td style="color: #DF5F00; font-weight: bold; padding: 2px; vertical-align: middle;">USD 228,70</td>
                                                        <td style="padding: 2px; vertical-align: middle;">
                                                            <a href="#" class="btn btn-success btn-sm">ON REQUEST</a>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td style="padding: 2px; vertical-align: middle;">STANDARD</td>
                                                        <td style="padding: 2px; vertical-align: middle;">D.BUFFET</td>
                                                        <td style="color: #DF5F00; font-weight: bold; padding: 2px; vertical-align: middle;">USD 228,70</td>
                                                        <td style="padding: 2px; vertical-align: middle;">
                                                            <a href="#" class="btn btn-success btn-sm">ON REQUEST</a>
                                                        </td>
                                                    </tr>
                                                </table>
                                            </td>
                                        </tr>
                                    </table>
                                            
                                    
                                </div>

                            </div>
                            
                            
                            
                            
                            
                            <div class="tab-pane" id="profile1">
                                <table width="100%" style="margin-top: -15px; margin-left: -15px;">
                                        <tr>
                                            <td rowspan="2" width="210" valign="top">
                                                <img src="<?php echo $_layoutParams['ruta_hoteles']; ?>1.jpg" width="200" class="img-thumbnail" style="margin-right: 10px;">
                                            </td>
                                            <td colspan="2">
                                                <p><b style="color:#FF9900; font-size:11px">DESCRIPCI&Oacute;N:</b><br> 
                                                    Contamos con una oferta de 157 habitaciones que incluyen la mejor vista al Lago Llanquihue y la belleza de los volcanes aleda&ntilde;os. Un lugar ideal para descansar en tus vacaciones.Nuestro hotel se encuentra emplazado en un gran edificio que se alza imponente sobre la ciudad de Puerto Varas con una arquitectura inconfundible. Somos la puerta de entrada a todos los atractivos de Puerto Varas, una ciudad del sur de Chile de naturaleza exuberante, gastronom&iacute;a excepcional y un rico patrimonio cultural.Lo invitamos a conocer nuestro servicio cuatro estrellas, sin&oacute;nimo de acogida, comodidad y confianza. Nuestra calidad es reconocida a nivel nacional e internacional, lo que le garantiza una grata estad&iacute;a en un incomparable centro de vacaciones.
                                                </p>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <p>
                                                   <b style="color:#FF9900; font-size:11px">SERVICIOS HOTEL:</b><br>
                                                    
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/restaurant.jpg" title="Restaurante">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/bar.jpg" title="Bar">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/room_service.jpg" title="Servicio a la Habitación">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/business_center.jpg" title="Business Center">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/internet.jpg" title="Internet Hotel">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/estacionamiento.jpg" title="Estacionamiento">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/piscina_desc.jpg" title="Piscina Descubierta">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/gimnasio.jpg" title="Gimnasio">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/spa.jpg" title="Spa">
                    				
                                                </p>
                                            </td>
                                            <td>
                                                <p>
                                                    
                                                    <b style="color:#FF9900; font-size:11px">SERVICIOS HABITACI&Oacute;N:</b><br> 
                                                    
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/aire_acondicionado.jpg" title="Aire Acondicionado">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/calefaccion.jpg" title="Calefaccion">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/habitacion_no_fum.jpg" title="No Fumadores">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/caja_de_seguridad.jpg" title="Caja Fuerte">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/minibar.jpg" title="Mini Bar">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/tv.jpg" title="Televisión">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/tv_cable.jpg" title="Tv Cable">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/telefono.jpg" title="Teléfono">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/internet.jpg" title="Internet Habitación">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/secador.jpg" title="Secador">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/barradeseguridad.jpg" title="Barra de Seguridad">
                    				
                                                </p>
                                            </td>
                                        </tr>
                                    </table>
                            </div>
                             <div class="tab-pane" id="messages1">Mapas</div>
                            </div>
                    </div>
                </div>

                
                
                
                
                
                
                
                <div class="panel panel-primary">
                    <div class="panel-heading" >
                        
                            <img src="<?php echo $_layoutParams['ruta_img']; ?>star_on.png" style="width: 20px; margin-top: -5px;">
                            <img src="<?php echo $_layoutParams['ruta_img']; ?>star_on.png" style="width: 20px; margin-top: -5px;">
                            <img src="<?php echo $_layoutParams['ruta_img']; ?>star_on.png" style="width: 20px; margin-top: -5px;">
                            <img src="<?php echo $_layoutParams['ruta_img']; ?>star_off.png" style="width: 20px; margin-top: -5px;">
                            <img src="<?php echo $_layoutParams['ruta_img']; ?>star_off.png" style=" width: 20px; margin-top: -5px;">
                             - APART HOTEL NERUDA
                        
                        <div class="options">
                          <ul class="nav nav-tabs">
                            <li class="active">
                              <a href="#home2" data-toggle="tab">Tarifas</a>
                            </li>
                            <li>
                                <a href="#profile2" data-toggle="tab">Ficha T&eacute;cnica</a>
                            </li>
                            <li>
                              <a href="#messages2" data-toggle="tab">Mapa</a>
                            </li>
                          </ul>
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="tab-content">
                            <div class="tab-pane active" id="home2" >
                                <div>
                                    
                                    <table width="100%"  style="margin-top: -15px; margin-left: -15px;">
                                        <tr>
                                            <td rowspan="2" width="210" valign="top">
                                                <img src="<?php echo $_layoutParams['ruta_hoteles']; ?>2.jpg" width="200" class="img-thumbnail" style="margin-right: 10px;">
                                            </td>
                                            <td>
                                                <P style="font-size:11px"><b style="color:#FF9900;">DIRECCI&Oacute;N:</b>  AV. CONDELL 40, PROVIDENCIA</P>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td valign="top">
                                                <!-- <hr> -->
                                                <table cellpadding="0" cellspacing="0" border="0" class="table table-striped" style="width: 72%; margin-left: 58px; margin-top: 10px; font-size:12px"> <!-- class="table table-striped table-bordered" -->
                                                    <tr>
                                                        <tr>
                                                            <th role="columnheader" style="padding-left: 2px;">Tipo Habitaci&oacute;n</th>
                                                            <th role="columnheader" style="padding-left: 2px;">Plan alimenticio</th>
                                                            <th role="columnheader" style="padding-left: 2px;">Precio estadia</th>
                                                            <th role="columnheader" style="padding-left: 2px;">Status</th>
                                                        </tr>
                                                    </tr>
                                                    <tr>
                                                        <td style="padding: 2px; vertical-align: middle;">STANDARD</td>
                                                        <td style="padding: 2px; vertical-align: middle;">D.BUFFET</td>
                                                        <td style="color: #DF5F00; font-weight: bold; padding: 2px; vertical-align: middle;">USD 228,70</td>
                                                        <td style="padding: 2px; vertical-align: middle;">
                                                            <a href="#" class="btn btn-success btn-sm" style="width: 88px;">AVAILABLE</a>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td style="padding: 2px; vertical-align: middle;">SUPERIOR</td>
                                                        <td style="padding: 2px; vertical-align: middle;">D.BUFFET</td>
                                                        <td style="color: #DF5F00; font-weight: bold; padding: 2px; vertical-align: middle;">USD 228,70</td>
                                                        <td style="padding: 2px; vertical-align: middle;">
                                                            <a href="#" class="btn btn-success btn-sm">ON REQUEST</a>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td style="padding: 2px; vertical-align: middle;">STANDARD</td>
                                                        <td style="padding: 2px; vertical-align: middle;">D.BUFFET</td>
                                                        <td style="color: #DF5F00; font-weight: bold; padding: 2px; vertical-align: middle;">USD 228,70</td>
                                                        <td style="padding: 2px; vertical-align: middle;">
                                                            <a href="#" class="btn btn-success btn-sm">ON REQUEST</a>
                                                        </td>
                                                    </tr>
                                                </table>
                                            </td>
                                        </tr>
                                    </table>
                                            
                                    
                                </div>

                            </div>
                            
                            
                            
                            
                            
                            <div class="tab-pane" id="profile2">
                                <table width="100%" style="margin-top: -15px; margin-left: -15px;">
                                        <tr>
                                            <td rowspan="2" width="210" valign="top">
                                                <img src="<?php echo $_layoutParams['ruta_hoteles']; ?>1.jpg" width="200" class="img-thumbnail" style="margin-right: 10px;">
                                            </td>
                                            <td colspan="2">
                                                <p><b style="color:#FF9900; font-size:11px">DESCRIPCI&Oacute;N:</b><br> 
                                                    Contamos con una oferta de 157 habitaciones que incluyen la mejor vista al Lago Llanquihue y la belleza de los volcanes aleda&ntilde;os. Un lugar ideal para descansar en tus vacaciones.Nuestro hotel se encuentra emplazado en un gran edificio que se alza imponente sobre la ciudad de Puerto Varas con una arquitectura inconfundible. Somos la puerta de entrada a todos los atractivos de Puerto Varas, una ciudad del sur de Chile de naturaleza exuberante, gastronom&iacute;a excepcional y un rico patrimonio cultural.Lo invitamos a conocer nuestro servicio cuatro estrellas, sin&oacute;nimo de acogida, comodidad y confianza. Nuestra calidad es reconocida a nivel nacional e internacional, lo que le garantiza una grata estad&iacute;a en un incomparable centro de vacaciones.
                                                </p>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <p>
                                                   <b style="color:#FF9900; font-size:11px">SERVICIOS HOTEL:</b><br>
                                                    
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/restaurant.jpg" title="Restaurante">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/bar.jpg" title="Bar">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/room_service.jpg" title="Servicio a la Habitación">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/business_center.jpg" title="Business Center">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/internet.jpg" title="Internet Hotel">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/estacionamiento.jpg" title="Estacionamiento">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/piscina_desc.jpg" title="Piscina Descubierta">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/gimnasio.jpg" title="Gimnasio">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/spa.jpg" title="Spa">
                    				
                                                </p>
                                            </td>
                                            <td>
                                                <p>
                                                    
                                                    <b style="color:#FF9900; font-size:11px">SERVICIOS HABITACI&Oacute;N:</b><br> 
                                                    
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/aire_acondicionado.jpg" title="Aire Acondicionado">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/calefaccion.jpg" title="Calefaccion">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/habitacion_no_fum.jpg" title="No Fumadores">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/caja_de_seguridad.jpg" title="Caja Fuerte">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/minibar.jpg" title="Mini Bar">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/tv.jpg" title="Televisión">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/tv_cable.jpg" title="Tv Cable">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/telefono.jpg" title="Teléfono">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/internet.jpg" title="Internet Habitación">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/secador.jpg" title="Secador">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/barradeseguridad.jpg" title="Barra de Seguridad">
                    				
                                                </p>
                                            </td>
                                        </tr>
                                    </table>
                            </div>
                            
                        
                            <div class="tab-pane" id="messages2">Mapas</div>
                        </div>
                    </div>
                </div>
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                <div class="panel panel-primary">
                    <div class="panel-heading" >
                        
                            <img src="<?php echo $_layoutParams['ruta_img']; ?>star_on.png" style="width: 20px; margin-top: -5px;">
                            <img src="<?php echo $_layoutParams['ruta_img']; ?>star_on.png" style="width: 20px; margin-top: -5px;">
                            <img src="<?php echo $_layoutParams['ruta_img']; ?>star_on.png" style="width: 20px; margin-top: -5px;">
                            <img src="<?php echo $_layoutParams['ruta_img']; ?>star_on.png" style="width: 20px; margin-top: -5px;">
                            <img src="<?php echo $_layoutParams['ruta_img']; ?>star_off.png" style=" width: 20px; margin-top: -5px;">
                             - NERUDA EXPRESS
                        
                        <div class="options">
                          <ul class="nav nav-tabs">
                            <li class="active">
                              <a href="#home3" data-toggle="tab">Tarifas</a>
                            </li>
                            <li>
                                <a href="#profile3" data-toggle="tab">Ficha T&eacute;cnica</a>
                            </li>
                            <li>
                              <a href="#messages3" data-toggle="tab">Mapa</a>
                            </li>
                          </ul>
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="tab-content">
                            <div class="tab-pane active" id="home3" >
                                <div>
                                    
                                    <table width="100%"  style="margin-top: -15px; margin-left: -15px;">
                                        <tr>
                                            <td rowspan="2" width="210" valign="top">
                                                <img src="<?php echo $_layoutParams['ruta_hoteles']; ?>1.jpg" width="200" class="img-thumbnail" style="margin-right: 10px;">
                                            </td>
                                            <td>
                                                <P style="font-size:11px"><b style="color:#FF9900;">DIRECCI&Oacute;N:</b> AV. PEDRO DE VALDIVIA 150, PROVIDENCIA</P>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td valign="top">
                                                <!-- <hr> -->
                                                <table cellpadding="0" cellspacing="0" border="0" class="table table-striped" style="width: 72%; margin-left: 58px; margin-top: 10px; font-size:12px"> <!-- class="table table-striped table-bordered" -->
                                                    <tr>
                                                        <tr>
                                                            <th role="columnheader" style="padding-left: 2px;">Tipo Habitaci&oacute;n</th>
                                                            <th role="columnheader" style="padding-left: 2px;">Plan alimenticio</th>
                                                            <th role="columnheader" style="padding-left: 2px;">Precio estadia</th>
                                                            <th role="columnheader" style="padding-left: 2px;">Status</th>
                                                        </tr>
                                                    </tr>
                                                    <tr>
                                                        <td style="padding: 2px; vertical-align: middle;">STANDARD</td>
                                                        <td style="padding: 2px; vertical-align: middle;">D.BUFFET</td>
                                                        <td style="color: #DF5F00; font-weight: bold; padding: 2px; vertical-align: middle;">USD 228,70</td>
                                                        <td style="padding: 2px; vertical-align: middle;">
                                                            <a href="#" class="btn btn-success btn-sm" style="width: 88px;">AVAILABLE</a>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td style="padding: 2px; vertical-align: middle;">SUPERIOR</td>
                                                        <td style="padding: 2px; vertical-align: middle;">D.BUFFET</td>
                                                        <td style="color: #DF5F00; font-weight: bold; padding: 2px; vertical-align: middle;">USD 228,70</td>
                                                        <td style="padding: 2px; vertical-align: middle;">
                                                            <a href="#" class="btn btn-success btn-sm">ON REQUEST</a>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td style="padding: 2px; vertical-align: middle;">STANDARD</td>
                                                        <td style="padding: 2px; vertical-align: middle;">D.BUFFET</td>
                                                        <td style="color: #DF5F00; font-weight: bold; padding: 2px; vertical-align: middle;">USD 228,70</td>
                                                        <td style="padding: 2px; vertical-align: middle;">
                                                            <a href="#" class="btn btn-success btn-sm">ON REQUEST</a>
                                                        </td>
                                                    </tr>
                                                </table>
                                            </td>
                                        </tr>
                                    </table>
                                            
                                    
                                </div>

                            </div>
                            
                            
                            
                            
                            
                            <div class="tab-pane" id="profile3">
                                <table width="100%" style="margin-top: -15px; margin-left: -15px;">
                                        <tr>
                                            <td rowspan="2" width="210" valign="top">
                                                <img src="<?php echo $_layoutParams['ruta_hoteles']; ?>1.jpg" width="200" class="img-thumbnail" style="margin-right: 10px;">
                                            </td>
                                            <td colspan="2">
                                                <p><b style="color:#FF9900; font-size:11px">DESCRIPCI&Oacute;N:</b><br> 
                                                    Contamos con una oferta de 157 habitaciones que incluyen la mejor vista al Lago Llanquihue y la belleza de los volcanes aleda&ntilde;os. Un lugar ideal para descansar en tus vacaciones.Nuestro hotel se encuentra emplazado en un gran edificio que se alza imponente sobre la ciudad de Puerto Varas con una arquitectura inconfundible. Somos la puerta de entrada a todos los atractivos de Puerto Varas, una ciudad del sur de Chile de naturaleza exuberante, gastronom&iacute;a excepcional y un rico patrimonio cultural.Lo invitamos a conocer nuestro servicio cuatro estrellas, sin&oacute;nimo de acogida, comodidad y confianza. Nuestra calidad es reconocida a nivel nacional e internacional, lo que le garantiza una grata estad&iacute;a en un incomparable centro de vacaciones.
                                                </p>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <p>
                                                   <b style="color:#FF9900; font-size:11px">SERVICIOS HOTEL:</b><br>
                                                    
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/restaurant.jpg" title="Restaurante">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/bar.jpg" title="Bar">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/room_service.jpg" title="Servicio a la Habitación">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/business_center.jpg" title="Business Center">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/internet.jpg" title="Internet Hotel">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/estacionamiento.jpg" title="Estacionamiento">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/piscina_desc.jpg" title="Piscina Descubierta">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/gimnasio.jpg" title="Gimnasio">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/spa.jpg" title="Spa">
                    				
                                                </p>
                                            </td>
                                            <td>
                                                <p>
                                                    
                                                    <b style="color:#FF9900; font-size:11px">SERVICIOS HABITACI&Oacute;N:</b><br> 
                                                    
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/aire_acondicionado.jpg" title="Aire Acondicionado">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/calefaccion.jpg" title="Calefaccion">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/habitacion_no_fum.jpg" title="No Fumadores">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/caja_de_seguridad.jpg" title="Caja Fuerte">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/minibar.jpg" title="Mini Bar">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/tv.jpg" title="Televisión">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/tv_cable.jpg" title="Tv Cable">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/telefono.jpg" title="Teléfono">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/internet.jpg" title="Internet Habitación">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/secador.jpg" title="Secador">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/barradeseguridad.jpg" title="Barra de Seguridad">
                    				
                                                </p>
                                            </td>
                                        </tr>
                                    </table>
                            </div>
                            
                            
                            <div class="tab-pane" id="messages3">Mapas</div>
                        </div>
                    </div>
                </div>

                
                
                
                
                
                
                
                <div class="panel panel-primary">
                    <div class="panel-heading" >
                        
                            <img src="<?php echo $_layoutParams['ruta_img']; ?>star_on.png" style="width: 20px; margin-top: -5px;">
                            <img src="<?php echo $_layoutParams['ruta_img']; ?>star_on.png" style="width: 20px; margin-top: -5px;">
                            <img src="<?php echo $_layoutParams['ruta_img']; ?>star_off.png" style="width: 20px; margin-top: -5px;">
                            <img src="<?php echo $_layoutParams['ruta_img']; ?>star_off.png" style="width: 20px; margin-top: -5px;">
                            <img src="<?php echo $_layoutParams['ruta_img']; ?>star_off.png" style=" width: 20px; margin-top: -5px;">
                             - APART HOTEL NERUDA
                        
                        <div class="options">
                          <ul class="nav nav-tabs">
                            <li class="active">
                              <a href="#home4" data-toggle="tab">Tarifas</a>
                            </li>
                            <li>
                                <a href="#profile4" data-toggle="tab">Ficha T&eacute;cnica</a>
                            </li>
                            <li>
                              <a href="#messages4" data-toggle="tab">Mapa</a>
                            </li>
                          </ul>
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="tab-content">
                            <div class="tab-pane active" id="home4" >
                                <div>
                                    
                                    <table width="100%"  style="margin-top: -15px; margin-left: -15px;">
                                        <tr>
                                            <td rowspan="2" width="210" valign="top">
                                                <img src="<?php echo $_layoutParams['ruta_hoteles']; ?>2.jpg" width="200" class="img-thumbnail" style="margin-right: 10px;">
                                            </td>
                                            <td>
                                                <P style="font-size:11px"><b style="color:#FF9900;">DIRECCI&Oacute;N:</b>  AV. CONDELL 40, PROVIDENCIA</P>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td valign="top">
                                                <!-- <hr> -->
                                                <table cellpadding="0" cellspacing="0" border="0" class="table table-striped" style="width: 72%; margin-left: 58px; margin-top: 10px; font-size:12px"> <!-- class="table table-striped table-bordered" -->
                                                    <tr>
                                                        <tr>
                                                            <th role="columnheader" style="padding-left: 2px;">Tipo Habitaci&oacute;n</th>
                                                            <th role="columnheader" style="padding-left: 2px;">Plan alimenticio</th>
                                                            <th role="columnheader" style="padding-left: 2px;">Precio estadia</th>
                                                            <th role="columnheader" style="padding-left: 2px;">Status</th>
                                                        </tr>
                                                    </tr>
                                                    <tr>
                                                        <td style="padding: 2px; vertical-align: middle;">STANDARD</td>
                                                        <td style="padding: 2px; vertical-align: middle;">D.BUFFET</td>
                                                        <td style="color: #DF5F00; font-weight: bold; padding: 2px; vertical-align: middle;">USD 228,70</td>
                                                        <td style="padding: 2px; vertical-align: middle;">
                                                            <a href="#" class="btn btn-success btn-sm" style="width: 88px;">AVAILABLE</a>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td style="padding: 2px; vertical-align: middle;">SUPERIOR</td>
                                                        <td style="padding: 2px; vertical-align: middle;">D.BUFFET</td>
                                                        <td style="color: #DF5F00; font-weight: bold; padding: 2px; vertical-align: middle;">USD 228,70</td>
                                                        <td style="padding: 2px; vertical-align: middle;">
                                                            <a href="#" class="btn btn-success btn-sm">ON REQUEST</a>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td style="padding: 2px; vertical-align: middle;">STANDARD</td>
                                                        <td style="padding: 2px; vertical-align: middle;">D.BUFFET</td>
                                                        <td style="color: #DF5F00; font-weight: bold; padding: 2px; vertical-align: middle;">USD 228,70</td>
                                                        <td style="padding: 2px; vertical-align: middle;">
                                                            <a href="#" class="btn btn-success btn-sm">ON REQUEST</a>
                                                        </td>
                                                    </tr>
                                                </table>
                                            </td>
                                        </tr>
                                    </table>
                                            
                                    
                                </div>

                            </div>
                            
                            
                            
                            
                            
                            <div class="tab-pane" id="profile4">
                                <table width="100%" style="margin-top: -15px; margin-left: -15px;">
                                        <tr>
                                            <td rowspan="2" width="210" valign="top">
                                                <img src="<?php echo $_layoutParams['ruta_hoteles']; ?>1.jpg" width="200" class="img-thumbnail" style="margin-right: 10px;">
                                            </td>
                                            <td colspan="2">
                                                <p><b style="color:#FF9900; font-size:11px">DESCRIPCI&Oacute;N:</b><br> 
                                                    Contamos con una oferta de 157 habitaciones que incluyen la mejor vista al Lago Llanquihue y la belleza de los volcanes aleda&ntilde;os. Un lugar ideal para descansar en tus vacaciones.Nuestro hotel se encuentra emplazado en un gran edificio que se alza imponente sobre la ciudad de Puerto Varas con una arquitectura inconfundible. Somos la puerta de entrada a todos los atractivos de Puerto Varas, una ciudad del sur de Chile de naturaleza exuberante, gastronom&iacute;a excepcional y un rico patrimonio cultural.Lo invitamos a conocer nuestro servicio cuatro estrellas, sin&oacute;nimo de acogida, comodidad y confianza. Nuestra calidad es reconocida a nivel nacional e internacional, lo que le garantiza una grata estad&iacute;a en un incomparable centro de vacaciones.
                                                </p>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <p>
                                                   <b style="color:#FF9900; font-size:11px">SERVICIOS HOTEL:</b><br>
                                                    
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/restaurant.jpg" title="Restaurante">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/bar.jpg" title="Bar">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/room_service.jpg" title="Servicio a la Habitación">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/business_center.jpg" title="Business Center">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/internet.jpg" title="Internet Hotel">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/estacionamiento.jpg" title="Estacionamiento">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/piscina_desc.jpg" title="Piscina Descubierta">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/gimnasio.jpg" title="Gimnasio">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/spa.jpg" title="Spa">
                    				
                                                </p>
                                            </td>
                                            <td>
                                                <p>
                                                    
                                                    <b style="color:#FF9900; font-size:11px">SERVICIOS HABITACI&Oacute;N:</b><br> 
                                                    
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/aire_acondicionado.jpg" title="Aire Acondicionado">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/calefaccion.jpg" title="Calefaccion">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/habitacion_no_fum.jpg" title="No Fumadores">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/caja_de_seguridad.jpg" title="Caja Fuerte">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/minibar.jpg" title="Mini Bar">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/tv.jpg" title="Televisión">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/tv_cable.jpg" title="Tv Cable">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/telefono.jpg" title="Teléfono">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/internet.jpg" title="Internet Habitación">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/secador.jpg" title="Secador">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/barradeseguridad.jpg" title="Barra de Seguridad">
                    				
                                                </p>
                                            </td>
                                        </tr>
                                    </table>
                            </div>
                            
                        
                            <div class="tab-pane" id="messages4">Mapas</div>
                        </div>
                    </div>
                </div>
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                <?php if(isset($this->paginacion)){ echo $this->paginacion; }else{ ?>
                <center>
                <div class="tab-pane active" id="dompaginate">
                    <ul class="pagination">
                      <li class="disabled"><a href="#">&ll;</a></li>
                      <li class="disabled"><a href="#">&lt;</a></li>
                      <li class="active"><a href="#">1</a></li>
                      <li><a href="#">2</a></li>
                      <li><a href="#">3</a></li>
                      <li><a href="#">4</a></li>
                      <li><a href="#">5</a></li>
                      <li><a href="#">&gt;</a></li>
                      <li><a href="#">&gg;</a></li>
                    </ul>
                </div>
                </center>
                <?php } ?>

            </div>
        </div> <!-- container -->
    </div> <!--wrap -->
</div> <!-- page-content -->