<div id="page-content">
    <div id='wrap'>
        <div id="page-heading">

            <h1>Programas</h1>

        </div>


        <div class="container">



            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-danger">

                        <div class="panel panel-info">
                            <div class="panel-heading">
                                <h4>Buscar Programas</h4>
                            </div>
                            <div class="panel-body">
                                <div class="row">


                                    <div class="col-md-12">


                                        <div id="divAlertWarHot" class="alert alert-dismissable alert-warning" style="display:none;">
                                            <strong>Atenci&oacute;n!</strong>
                                            Debe ingresar una <b>Ciudad</b>, <b>Nombre de hotel</b> o seleccionar una <b>Categoria</b>.
                                            <button type="button" class="close" onClick="muestraOculta('divAlertWarHot', '2')">&times;</button>
                                        </div>

                                        

                                    </div>

                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div> 
</div>