<div id="page-content">
    <div id='wrap'>
        <div id="page-heading">
            <h1>Hoteles en SANTIAGO/CHILE</h1>
        </div>
		
        
        <div class="container">
            <div class="row">
                
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h4>NERUDA EXPRESS - <b>Direcci&oacute;n:</b> BERNARDO O HIGGINS N&deg; 816</h4>
                        <div class="options">
                          <ul class="nav nav-tabs">
                            <li class="active">
                              <a href="#home1" data-toggle="tab">Home</a>
                            </li>
                            <li>
                              <a href="#profile1" data-toggle="tab">Fotos</a>
                            </li>
                            <li>
                              <a href="#messages1" data-toggle="tab">Mapa</a>
                            </li>
                          </ul>
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="tab-content">
                            <div class="tab-pane active" id="home1" >
                                <div class="date"  style="margin-bottom: 10px;  margin-left: 50px;">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>star_on.png" width="20">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>star_on.png" width="20">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>star_on.png" width="20">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>star_off.png" width="20">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>star_off.png" width="20">
                                </div>
                                <div>
                                    
                                    <table width="100%">
                                        <tr>
                                            <td rowspan="2" width="210">
                                                <img src="<?php echo $_layoutParams['ruta_hoteles']; ?>1.jpg" width="200" class="img-thumbnail" style="margin-right: 10px;">
                                            </td>
                                            <td>
                                                <p>
                                                   <b style="color:#FF9900; font-size:11px">SERVICIOS HOTEL:</b><br>
                                                    
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/restaurant.jpg" title="Restaurante">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/bar.jpg" title="Bar">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/room_service.jpg" title="Servicio a la Habitación">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/business_center.jpg" title="Business Center">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/internet.jpg" title="Internet Hotel">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/estacionamiento.jpg" title="Estacionamiento">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/piscina_desc.jpg" title="Piscina Descubierta">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/gimnasio.jpg" title="Gimnasio">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/spa.jpg" title="Spa">
                    				
                                                </p>
                                            </td>
                                            <td>
                                                <p>
                                                    
                                                    <b style="color:#FF9900; font-size:11px">SERVICIOS HABITACI&Oacute;N:</b><br> 
                                                    
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/aire_acondicionado.jpg" title="Aire Acondicionado">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/calefaccion.jpg" title="Calefaccion">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/habitacion_no_fum.jpg" title="No Fumadores">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/caja_de_seguridad.jpg" title="Caja Fuerte">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/minibar.jpg" title="Mini Bar">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/tv.jpg" title="Televisión">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/tv_cable.jpg" title="Tv Cable">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/telefono.jpg" title="Teléfono">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/internet.jpg" title="Internet Habitación">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/secador.jpg" title="Secador">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/barradeseguridad.jpg" title="Barra de Seguridad">
                    				
                                                </p>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td colspan="2">
                                                <hr>
                                                <table align="left" style="margin-left: 10px;" >
                                                    <tr>
                                                        <td width="100">STANDARD</td><td width="100">D.BUFFET</td>
                                                        <td>
                                                            <a href="#" class="btn btn-success">&nbsp;&nbsp;AVAILABLE&nbsp;&nbsp;</a>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td>SUPERIOR</td><td>D.BUFFET</td>
                                                        <td>
                                                            <a href="#" class="btn btn-success">ON REQUEST</a>
                                                        </td>
                                                    </tr>
                                                </table>
                                            </td>
                                        </tr>
                                    </table>
                                            
                                    
                                </div>

                            </div>
                            <div class="tab-pane" id="profile1">Fotos hotel</div>
                             <div class="tab-pane" id="messages1">Mapas</div>
                            </div>
                    </div>
                </div>

                
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h4>APART HOTEL NERUDA - <b>Direcci&oacute;n:</b> AV. CONDELL 40, PROVIDENCIA</h4>
                        <div class="options">
                          <ul class="nav nav-tabs">
                            <li class="active">
                              <a href="#home2" data-toggle="tab">Home</a>
                            </li>
                            <li>
                              <a href="#fotos2" data-toggle="tab">Fotos</a>
                            </li>
                            <li>
                              <a href="#mapa2" data-toggle="tab">Mapa</a>
                            </li>
                          </ul>
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="tab-content">
                            <div class="tab-pane active" id="home2">
                                <div class="date" style="margin-bottom: 10px; margin-left: 50px;">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>star_on.png" width="20">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>star_on.png" width="20">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>star_on.png" width="20">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>star_on.png" width="20">
                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>star_off.png" width="20">
                                </div>
                                
                                
                                <div>
                                    
                                    <table width="100%">
                                        <tr>
                                            <td rowspan="2" width="210">
                                                <img src="<?php echo $_layoutParams['ruta_hoteles']; ?>2.jpg" width="200" class="img-thumbnail" style="margin-right: 10px;">
                                            </td>
                                            <td>
                                                <p>
                                                   <b style="color:#FF9900; font-size:11px">SERVICIOS HOTEL:</b><br>
                                                    
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/restaurant.jpg" title="Restaurante">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/bar.jpg" title="Bar">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/room_service.jpg" title="Servicio a la Habitación">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/business_center.jpg" title="Business Center">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/internet.jpg" title="Internet Hotel">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/estacionamiento.jpg" title="Estacionamiento">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/piscina_desc.jpg" title="Piscina Descubierta">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/gimnasio.jpg" title="Gimnasio">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/spa.jpg" title="Spa">
                    				
                                                </p>
                                            </td>
                                            <td>
                                                <p>
                                                    
                                                    <b style="color:#FF9900; font-size:11px">SERVICIOS HABITACI&Oacute;N:</b><br> 
                                                    
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/aire_acondicionado.jpg" title="Aire Acondicionado">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/calefaccion.jpg" title="Calefaccion">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/habitacion_no_fum.jpg" title="No Fumadores">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/caja_de_seguridad.jpg" title="Caja Fuerte">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/minibar.jpg" title="Mini Bar">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/tv.jpg" title="Televisión">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/tv_cable.jpg" title="Tv Cable">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/telefono.jpg" title="Teléfono">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/internet.jpg" title="Internet Habitación">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/secador.jpg" title="Secador">
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>hotel/barradeseguridad.jpg" title="Barra de Seguridad">
                    				
                                                </p>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td colspan="2">
                                                <hr>
                                                <table align="left" style="margin-left: 10px;" >
                                                    <tr>
                                                        <td width="100">STANDARD</td><td width="100">D.BUFFET</td>
                                                        <td>
                                                            <a href="#" class="btn btn-success">&nbsp;&nbsp;AVAILABLE&nbsp;&nbsp;</a>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td>SUPERIOR</td><td>D.BUFFET</td>
                                                        <td>
                                                            <a href="#" class="btn btn-success">ON REQUEST</a>
                                                        </td>
                                                    </tr>
                                                </table>
                                            </td>
                                        </tr>
                                    </table>
                                            
                                    
                                </div>
                                
                            </div>
                            <div class="tab-pane" id="fotos2">Fotos hotel</div>
                             <div class="tab-pane" id="mapa2">Mapas</div>
                        </div>
                    </div>
                </div>
                
                <?php if(isset($this->paginacion)){ echo $this->paginacion; }else{ ?>
                <center>
                <div class="tab-pane active" id="dompaginate">
                    <ul class="pagination">
                      <li class="disabled"><a href="#">&ll;</a></li>
                      <li class="disabled"><a href="#">&lt;</a></li>
                      <li class="active"><a href="#">1</a></li>
                      <li><a href="#">2</a></li>
                      <li><a href="#">3</a></li>
                      <li><a href="#">4</a></li>
                      <li><a href="#">5</a></li>
                      <li><a href="#">&gt;</a></li>
                      <li><a href="#">&gg;</a></li>
                    </ul>
                </div>
                </center>
                <?php } ?>

            </div>
        </div> <!-- container -->
    </div> <!--wrap -->
</div> <!-- page-content -->