<!-- <div id="page-content" style="min-height: 948px"> -->
<div id="page-content">
    <div id='wrap'>
        <div id="page-heading">
            <ol class="breadcrumb">
                <li><a href="<?php echo BASE_URL . 'sistema'; ?>">Inicio</a></li>
                <li class="active">Carro de compras</li>
            </ol>
            
            <h1>Carro de compras</h1>
        </div>
		
        
        <div class="container">

			

			
            <div class="row">
                <div class="col-lg-12">
                    
                    
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <h4>Detalle</h4>
                        </div>
                        <div class="panel-body">
		  	
                            <div class="tab-content">
                                <div class="tab-pane active" id="domwizard">
                                    <div id="basicwizard" class="form-horizontal">
                                        
                                        
                                        <fieldset title="Paso 1">
                                            <legend style="padding-bottom: 0px; margin-bottom: 0px;"></legend>
                                                
                                                        <div class="table-responsive">


                                                            <table class="table table-bordered table-striped"  style="font-size: 11px;" id="carroTable">
                                                                
                                                               <?php 
                                                               if($this->objCarro)
                                                               {
                                                                   ?>
                                                                   <thead>
                                                                    <tr>
                                                                        <th width="70">Status</th>
                                                                        <th>Servicio</th>
                                                                        <th>Habitaci&oacute;n</th>
                                                                        <th>P.A.</th>
                                                                        <th>N&deg; hab.</th>
                                                                        <th>A.</th>
                                                                        <th>C.</th>
                                                                        <th>Pais</th>
                                                                        <th>Ciudad</th>
                                                                        <th>Fecha In</th>
                                                                        <th>Fecha Out</th>
                                                                        <th>Vuelo</th>
                                                                        <th>Total</th>
                                                                        <th></th>
                                                                    </tr>
                                                                </thead>
                                                                  <?php
                                                                   $totalCompras=0;
                                                                   foreach($this->objCarro as $objCar )
                                                                   {
                                                               ?>   
                                                                
                                                                        <tbody>
                                                                            <tr>
                                                                                <th><span class="label label-success"><?php echo $objCar->getStatus(); ?></span></th>
                                                                                <td><?php echo $objCar->getServicio(); ?></td>
                                                                                <td class="text-muted"><?php echo $objCar->getHabitacion() ?></td>
                                                                                <td><?php echo $objCar->getPa() ?></td>
                                                                                <td><?php echo $objCar->getNhab() ?></td>
                                                                                <td><?php echo $objCar->getA() ?></td>
                                                                                <td class="text-muted"><?php echo $objCar->getC() ?></td>
                                                                                <td><?php  echo $objCar->getPais() ?></td>
                                                                                <td><?php echo $objCar->getCiudad() ?></td>
                                                                                <td><?php echo Funciones::invertirFecha($objCar->getFecha_in(), '-', '/') ?></td>
                                                                                <td class="text-muted"><?php if($objCar->getFecha_out()=='0000-00-00'){echo "";} else {echo Funciones::invertirFecha($objCar->getFecha_out(),'-','/');} ?></td>
                                                                                <td><?php echo $objCar->getVuelo() ?></td>
                                                                                <td style="color: #DF5F00; font-weight: bold;"><?php echo $objCar->getTotal() ?></td>                                                                               
                                                                                <td></td>
                                                                            </tr>
                                                                            
                                                                
                                                                <?php
                                                                   }
                                                                   ?>
                                                                            <tr>
                                                                                <td colspan="12" align="right">Total</td>
                                                                                <td style="color: #DF5F00; font-weight: bold;"><?php echo $totalCompras+=$objCar->getTotal()?></td>
                                                                                <td></td>
                                                                            </tr>
                                                                        </tbody>
                                                                        </table>
                                                                 <?php
                                                                 ?>
                                                            
                                                                             
                                                                 <?php
                                                               }
                                                               else{
                                                                ?>  
                                                                        <tr>
                                                                            <td>
                                                                        <center><strong>No se encontraron reservas.</strong></center>
                                                                            </td>
                                                                        </tr>
                                                                                                                                    </table>
                                                            </table>
                                                        

                                                                <?php   
                                                               }
                           
                                                                ?>
                                                           <span class="pull-right">
                                                                                <input type="button" class="finish btn-primary btn" id="btnSig_P1" value="Siguiente" />
                                                                            </span>
                                                                            <br>      
                                                        </div>
                                            
                                        </fieldset>
   
                                        <fieldset title="Paso 2">
                                            
                                            <legend>Detalle de pasajeros</legend>
                                            <form class="frm_paso2">
                                            <div class="table-responsive">
                                      
                                               
                                                <table class="table table-bordered table-striped" style="font-size: 11px; width: 600px;" align="center">
                                                    <tbody> 
                                                    <?php
                                                    if(Session::get('sess_pBP_cntHab')){
                                                    for($i = 1; $i<=Session::get('sess_pBP_cntHab'); $i++){  
                                                    ?>
                                                        <thead>
                                                        <tr>
                                                            <th width="100">Habitaci&oacute;n <?php echo $i ?></th>
                                                            <th>Nombres</th>
                                                            <th>Apellidos</th>
                                                        </tr>
                                                       </thead>
                                                       <?php
                                                       if(Session::get('sess_BP_Adl_'.$i)){
                                                       for($j = 1; $j <=Session::get('sess_BP_Adl_'.$i) ; $j++){                                          
                                                       ?>
                                                        <tr>
                                                            <th>Adulto <?php echo $j;?></th>
                                                            <td><input type="text" class="form-control" id="Carr_txtNombrePas_<?php echo $i.'_'.$j?>" name="Carr_txtNombrePas_<?php echo $i.'_'.$j?>" value=""></td> <?php //if(isset($mL_ini)){ echo $mL_ini; } ?>
                                                            <td><input type="text" class="form-control" id="Carr_txtApellidoPas_<?php echo $i.'_'.$j?>" name="Carr_txtApellidoPas_<?php echo $i.'_'.$j?>" value=""></td><?php //if(isset($mL_ini)){ echo $mL_ini; } ?>
                                                        </tr>
                                                       <?php
                                                           }
                                                       }
                                                    }
                                                    ?>
                          
                                                    </tbody>
                                                

                                                </table>
                                                
                                                <table class="table table-bordered table-striped" style="font-size: 11px; width: 600px;" align="center">
                                                    <tr>
                                                        <td>Escriba una nota</td>
                                                        <td><textarea style='height: 150px;' id="Carr_textAreaNota" name="Carr_textAreaNota" class="form-control" value="Escriba una nota..."></textarea></td>
                                                        
                                                    </tr>
                                                </table>
                                           <?php
                                                    }
                                                    //Session::destroy('sess_pBP_cntHab');
                                                   
                                           ?>

                                            </div>
                                            
                                            <span class="pull-right">
                                                <input type="button" class="finish btn-default btn" id="btnAtr_P2" value="Atras" />
                                                <input type="button" class="finish btn-primary btn" id="btnSig_P2" value="Siguiente" onclick="carroAdl('<?php echo BASE_URL?>sistema/paso3');" />
                                            </span>
                                            <br>
                                            </form>
                                        </fieldset>
    
                                        <fieldset title="Paso 3">
                                            <legend>SOLICITUD DE RESERVA</legend>
                                             <div class="panel panel-info" id="div_paso3">
                                                 
                                            </div>
                                        </fieldset>
                                    </div>
                                </div>


                            </div>

                        </div>
                    </div>
                    
                    
                </div>
            </div>

            


			

        </div> <!-- container -->
    </div> <!--wrap -->
</div> <!-- page-content -->

<script type="text/javascript">
$('#btnSig_P1').on('click',function(){
        $('#basicwizard-head-0').removeClass('stepy-active');
        $('#basicwizard-step-0').css('display', 'none');
        
        $('#basicwizard-head-1').addClass('stepy-active');
        $('#basicwizard-step-1').css('display', 'block');
});


$('#btnAtr_P2').on('click',function(){
        
        $('#basicwizard-head-1').removeClass('stepy-active');
        $('#basicwizard-step-1').css('display', 'none');
        
        
        $('#basicwizard-head-0').addClass('stepy-active');
        $('#basicwizard-step-0').css('display', 'block');
        
});
$('#btnSig_P2').on('click',function(){
        $('#basicwizard-head-1').removeClass('stepy-active');
        $('#basicwizard-step-1').css('display', 'none');
        
        //var a = $('#carroTable').html();
        //$('#carroTableDet').html(a);
        $('#basicwizard-head-2').addClass('stepy-active');
        $('#basicwizard-step-2').css('display', 'block');
});

function carroAdl(url){
 var formData = new FormData($(".frm_paso2")[0]);
        $.ajax({
             type:"POST", 
             url:url,
             data:formData,
             cache: false,
             contentType: false,
             processData: false,
             beforeSend: function () {
             },
             success:function(data)
             {
                 alert("ok");
                 $("#div_paso3").html(data);
             }
         });   
 
}



$('#btnAtr_P3').on('click',function(){
        $('#basicwizard-head-2').removeClass('stepy-active');
        $('#basicwizard-step-2').css('display', 'none');
        
       
        
        $('#basicwizard-head-1').addClass('stepy-active');
        $('#basicwizard-step-1').css('display', 'block');
});
</script>