<!-- <div id="page-content" style="min-height: 948px"> -->
<div id="page-content">
    <div id='wrap'>
        <div id="page-heading">
            <h1>Carro de compras</h1>
        </div>
		
        
        <div class="container">

			

			
            <div class="row">
                <div class="col-lg-12">
                    
                    
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <h4>Detalle</h4>
                        </div>
                        <div class="panel-body">
		  	
                            <div class="tab-content">
                                <div class="tab-pane active" id="domwizard">
                                    <form action="#" id="basicwizard" class="form-horizontal">
                                        
                                        
                                        <fieldset title="Paso 1">
                                            <legend style="padding-bottom: 0px; margin-bottom: 0px;"></legend>
                                                
                                                        <div class="table-responsive">


                                                            <table class="table table-bordered table-striped" style="font-size: 11px;">
                                                                <thead>
                                                                    <tr>
                                                                        <th width="70"></th>
                                                                        <th>Servicio</th>
                                                                        <th>Habitaci&oacute;n</th>
                                                                        <th>P.A.</th>
                                                                        <th>N&deg; hab.</th>
                                                                        <th>A.</th>
                                                                        <th>C.</th>
                                                                        <th>Pais</th>
                                                                        <th>Ciudad</th>
                                                                        <th>Fecha In</th>
                                                                        <th>Fecha Out</th>
                                                                        <th>Vuelo</th>
                                                                        <th>Total</th>
                                                                        <th></th>
                                                                    </tr>
                                                                </thead>

                                                                <tbody>
                                                                    <tr>
                                                                        <th><span class="label label-success">AVAILABLE</span></th>
                                                                        <td class="text-muted">None (auto)</td>
                                                                        <td>100%</td>
                                                                        <td>100%</td>
                                                                        <td>100%</td>
                                                                        <td class="text-muted">None (auto)</td>
                                                                        <td>100%</td>
                                                                        <td>100%</td>
                                                                        <td>100%</td>
                                                                        <td class="text-muted">None (auto)</td>
                                                                        <td>100%</td>
                                                                        <td>100%</td>
                                                                        <td style="color: #DF5F00; font-weight: bold;">USD 228,70</td>
                                                                        <td></td>
                                                                    </tr>
                                                                    <tr>
                                                                        <th><span class="label label-success">AVAILABLE</span></th>
                                                                        <td class="text-muted">None (auto)</td>
                                                                        <td>100%</td>
                                                                        <td>100%</td>
                                                                        <td>100%</td>
                                                                        <td class="text-muted">None (auto)</td>
                                                                        <td>100%</td>
                                                                        <td>100%</td>
                                                                        <td>100%</td>
                                                                        <td class="text-muted">None (auto)</td>
                                                                        <td>100%</td>
                                                                        <td>100%</td>
                                                                        <td style="color: #DF5F00; font-weight: bold;">USD 228,70</td>
                                                                        <td></td>
                                                                    </tr>
                                                                    <tr>
                                                                        <th><span class="label label-primary">ON REQUEST</span></th>
                                                                        <td class="text-muted">None (auto)</td>
                                                                        <td>100%</td>
                                                                        <td>100%</td>
                                                                        <td>100%</td>
                                                                        <td class="text-muted">None (auto)</td>
                                                                        <td>100%</td>
                                                                        <td>100%</td>
                                                                        <td>100%</td>
                                                                        <td class="text-muted">None (auto)</td>
                                                                        <td>100%</td>
                                                                        <td>100%</td>
                                                                        <td style="color: #DF5F00; font-weight: bold;">USD 228,70</td>
                                                                        <td></td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td colspan="12" align="right">Total</td>
                                                                        <td style="color: #DF5F00; font-weight: bold;">USD 228,70</td>
                                                                        <td></td>
                                                                    </tr>
                                                                </tbody>
                                                            </table>



                                                        </div>
                                            <span class="pull-right">
                                                <input type="button" class="finish btn-primary btn" id="btnSig_P1" value="Siguiente" />
                                            </span>
                                            <br>
                                        </fieldset>
                                        
                                        
                                        
                                        
                                        
                                        
                                        
                                        
                                        
                                        
                                        <fieldset title="Paso 2">
                                            <legend>Detalle de pasajeros</legend>
                                            
                                            <div class="table-responsive">


                                                <table class="table table-bordered table-striped" style="font-size: 11px; width: 600px;" align="center">
                                                    <thead>
                                                        <tr>
                                                            <th width="100">Habitacion 1</th>
                                                            <th>Nombres</th>
                                                            <th>Apellidos</th>
                                                        </tr>
                                                    </thead>

                                                    <tbody>
                                                        <tr>
                                                            <th>Adulto 1</th>
                                                            <td><input type="text" class="form-control" id="Carr_txtNombrePas_1" name="Carr_txtNombrePas_1" value="<?php echo $mL_ini; ?>"></td>
                                                            <td><input type="text" class="form-control" id="Carr_txtApellidoPas_1" name="Carr_txtApellidoPas_1" value="<?php echo $mL_ini; ?>"></td>
                                                        </tr>
                                                        <tr>
                                                            <th>Adulto 1</th>
                                                            <td><input type="text" class="form-control" id="Carr_txtNombrePas_1" name="Carr_txtNombrePas_1" value="<?php echo $mL_ini; ?>"></td>
                                                            <td><input type="text" class="form-control" id="Carr_txtApellidoPas_1" name="Carr_txtApellidoPas_1" value="<?php echo $mL_ini; ?>"></td>
                                                        </tr>
                                                        <tr>
                                                            <th>Adulto 1</th>
                                                            <td><input type="text" class="form-control" id="Carr_txtNombrePas_1" name="Carr_txtNombrePas_1" value="<?php echo $mL_ini; ?>"></td>
                                                            <td><input type="text" class="form-control" id="Carr_txtApellidoPas_1" name="Carr_txtApellidoPas_1" value="<?php echo $mL_ini; ?>"></td>
                                                        </tr>
                                                    </tbody>
                                                </table>



                                            </div>
                                            
                                            <span class="pull-right">
                                                <input type="button" class="finish btn-default btn" id="btnAtr_P2" value="Atras" />
                                                <input type="button" class="finish btn-primary btn" id="btnSig_P2" value="Siguiente" />
                                            </span>
                                            <br>
                                        </fieldset>
                                        
                                        
                                        
                                        
                                        
                                        
                                        
                                        
                                        
                                        
                                        <fieldset title="Paso 3">
                                            <legend>SOLICITUD DE RESERVA</legend>
                                            <div class="row">
                                                    <label class="col-md-3 control-label">Lorem Ipsum</label>
                                                    <div class="col-md-9">
                                                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam, quis autem deleniti animi eum a eaque sint voluptatibus labore possimus accusantium molestias magnam cum officiis qui neque minima assumenda facere aut repellat delectus. Soluta incidunt pariatur natus voluptatum voluptatibus culpa blanditiis. Inventore, repellendus, at veniam magnam quisquam necessitatibus modi est qui deserunt. Dicta, excepturi, iusto, maiores perferendis rem officiis est voluptas possimus laudantium fugit veritatis!</p>
                                                            <p>By clicking Finish you agree that you accept the Terms &amp; Conditions</p>
                                                    </div>
                                            </div>
                                            
                                            <span class="pull-right">
                                                <input type="button" class="finish btn-default btn" id="btnAtr_P3" value="Atras" />
                                                <input type="submit" class="finish btn-success btn" value="Reservar" />
                                            </span>
                                            <br>
                                        </fieldset>
                                    </form>
                                </div>


                            </div>

                        </div>
                    </div>
                    
                    
                </div>
            </div>

            


			

        </div> <!-- container -->
    </div> <!--wrap -->
</div> <!-- page-content -->

<script type="text/javascript">
$('#btnSig_P1').on('click',function(){
        $('#basicwizard-head-0').removeClass('stepy-active');
        $('#basicwizard-step-0').css('display', 'none');
        
        $('#basicwizard-head-1').addClass('stepy-active');
        $('#basicwizard-step-1').css('display', 'block');
});


$('#btnAtr_P2').on('click',function(){
        $('#basicwizard-head-1').removeClass('stepy-active');
        $('#basicwizard-step-1').css('display', 'none');
        
        $('#basicwizard-head-0').addClass('stepy-active');
        $('#basicwizard-step-0').css('display', 'block');
});
$('#btnSig_P2').on('click',function(){
        $('#basicwizard-head-1').removeClass('stepy-active');
        $('#basicwizard-step-1').css('display', 'none');
        
        $('#basicwizard-head-2').addClass('stepy-active');
        $('#basicwizard-step-2').css('display', 'block');
});


$('#btnAtr_P3').on('click',function(){
        $('#basicwizard-head-2').removeClass('stepy-active');
        $('#basicwizard-step-2').css('display', 'none');
        
        $('#basicwizard-head-1').addClass('stepy-active');
        $('#basicwizard-step-1').css('display', 'block');
});
</script>