<script>
$(function()
{
	$( "#txtFechaDesde-ConsRes" ).datepicker({
		defaultDate: "+1w",
		changeMonth: true,
		numberOfMonths: 2,
		monthNames: ['Enero','Febrero','Marzo','Abril','Mayo','Junio',
		'Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'],
		monthNamesShort: ['Ene','Feb','Mar','Abr','May','Jun',
		'Jul','Ago','Sep','Oct','Nov','Dic'],
		dayNames: ['Domingo','Lunes','Martes','Mi&eacute;rcoles','Jueves','Viernes','S&aacute;bado'],
		dayNamesMin: ['Do','Lu','Ma','Mi','Ju','Vi','S&aacute;'],
		dateFormat: 'dd/mm/yy',
		firstDay: 1,
		onSelect: function( selectedDate ){
			$( "#txtFechaHasta-ConsRes" ).datepicker( "option", "minDate", selectedDate );
		}
	});

	$( "#txtFechaHasta-ConsRes" ).datepicker({
		minDate: +1,
		defaultDate: "+1w",
		changeMonth: true,
		numberOfMonths: 2,
		monthNames: ['Enero','Febrero','Marzo','Abril','Mayo','Junio',
		'Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'],
		monthNamesShort: ['Ene','Feb','Mar','Abr','May','Jun',
		'Jul','Ago','Sep','Oct','Nov','Dic'],
		dayNames: ['Domingo','Lunes','Martes','Mi&eacute;rcoles','Jueves','Viernes','S&aacute;bado'],
		dayNamesMin: ['Do','Lu','Ma','Mi','Ju','Vi','S&aacute;'],
		dateFormat: 'dd/mm/yy',
		firstDay: 1,
		onSelect: function( selectedDate ) {
			$( "#txtFechaDesde-ConsRes" ).datepicker( "option", "maxDate", selectedDate );
		}
	});
});
</script>

<div id="page-content">
	<div id='wrap'>
		<div id="page-heading">
        
			<!-- <ol class="breadcrumb">
				<li><a href="index.php">Dashboard</a></li>
				<li>UI Components</li>
				<li class="active">Tabs &amp; Accordions</li>
			</ol> -->

			<h1>Consultar Booking</h1>
		</div>
		
        
        <div class="container">

			

			<div class="row">
				<div class="col-md-12">
					<div class="panel panel-danger">
					  
					  
						<div class="panel panel-info">
                        <div class="panel-heading">
                            <h4>Buscar booking</h4>
                        </div>
                        <div class="panel-body">
                            <div class="row">
                            
                                <div class="col-md-12">
                                    
                                    <form method="post" id="frmConsRes" action="<?php echo BASE_URL ?>process/consBooking">
                                    <table align="center" cellspacing="5" cellpadding="5">
                                        <tr>
 	                                       <td>Fecha desde:</td>
                                           <td>
                                           		<input type="text" id="txtFechaDesde-ConsRes" name="txtFechaDesde-ConsRes" style="width:100px" value="<?php echo $this->CR_fechaDesde; ?>">
                                           </td>
                                           <td>Fecha hasta:</td>
                                           <td>
                                           		<input type="text" id="txtFechaHasta-ConsRes" name="txtFechaHasta-ConsRes" style="width:100px" value="<?php echo $this->CR_fechaHasta; ?>">
                                           </td>
                                           <td rowspan="2">&nbsp;&nbsp;&nbsp;
                                           <input type="button"  id="btnConsBooking" class="btn btn-primary" value="Buscar">
                                           <img id="imgLoading" src="<?php echo $_layoutParams['ruta_img']; ?>loading.gif" style="display:none" width="32" border="0" />
                                           </td>
                                           <?php
                                           if(Session::get('sess_pCR_fechaDesde')){
                                           ?>
                                           <td><th width="10%"></th></td>
                                           <td> <center><img width="50" height="50" src="<?php echo $_layoutParams['ruta_img']; ?>excel.png"></center><br>
                                               <a href="<?php echo BASE_URL ?>sistema/crearExcelDet" >Generar Excel con Detalle </a>| 
                                                <a href="<?php echo BASE_URL ?>sistema/crearExcel">Generar Excel sin Detalle </a></td>
                                            
                                          <?php
                                           }
                                            ?>   
                                        </tr>
                                        <tr>
 	                                       <td>Fecha reserva:</td>
                                           <td><input type="radio" id="rdbReserva" name="rdbFecha" value="1" <?php echo $this->rdbRes; ?>></td>
                                           <td>Fecha viaje:</td>
                                           <td><input type="radio" id="rdbViaje" name="rdbFecha" value="2" <?php echo $this->rdbVia; ?>></td>     
                                        </tr>
                                    </table>
                                    </form>
                                    
                                </div>
                                
                            </div>
                        </div>
                    </div>	
								
								
								

					  
					</div>
                    
                    
                    <?php
                    if(Session::get('sess_pCR_fechaDesde'))
					{
					?>
                    <script>
					$('#btnConsBooking').delay( 10 ).fadeOut( 10 );
					$('#btnConsBooking').animate({
										'display': 'none'
									});
					$('#imgLoading').fadeIn( 100 );
					$('#imgLoading').animate({
										'display': 'block'
									});
					</script>
                    
                    	<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
								<div class="modal-dialog">
									<div class="modal-content">
										<div class="modal-header">
											<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
											<h4 class="modal-title">Carta de confirmaci&oacute;n</h4>
										</div>
										
                                        <div class="modal-body" id="divCartaConfirm"></div>
                                        
										<div class="modal-footer">
											<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
											<!-- <button type="button" class="btn btn-primary">Save changes</button> -->
										</div>
									</div><!-- /.modal-content -->
								</div><!-- /.modal-dialog -->
							</div><!-- /.modal -->

                    
                    
                    <div class="panel panel-sky" id="contenedorBusqueda" style="display:none">
                        <div class="panel-heading">
                            <h4>Resultado de la busqueda</h4>
                        </div>
                        <div class="panel-body collapse in">
                            <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered datatables" id="example">
                                <thead>
                                    <tr style="background-color:#76c4ed;">
                                        <th width="39">Estado</th>
                                        <th width="110">Fecha</th>
                                        <th width="110">Fecha In</th>
                                        <th width="70">File</th>
                                        <th>Cliente</th>
                                        <th>Vendedor</th>
                                        <th>Pasajero</th>
                                        <th width="110">Total</th>
                                        <th width="39">Vou</th>
                                        <th width="39">Reserva</th>
                                    </tr>
                                </thead>
                                <tbody>
                                
                                 <?php
                                    if($this->getBookings)
                                    { 
                                            foreach($this->getBookings as $columRes)
                                            {
                                                    //$valorVenta =intval($columRes["id_booking"]);
                                                    $cR_valorTotal= number_format(trim($columRes->getTotal()), 0, ',', '.');;
                                                    $cR_moneda = Funciones::getTipoMoneda(trim($columRes->getMoneda()));
                                                    $cR_fecha= trim($columRes->getFecha());
                                                    $cR_fViaje= trim($columRes->getFechaIn());
                                                    $cR_booking=trim($columRes->getId());
                                                    $cR_nFile= Funciones::add_ceros($cR_booking,6);
                                                    $cR_agencia= trim($columRes->getAgencia());
                                                    $cR_vendedor= trim($columRes->getNombreUser()).' '.$columRes->getApellidoUser();
                                                    $cR_pasajero= trim($columRes->getNomPax());
                                                    $cR_voucher= trim($columRes->getVoucher());
                                                    /*$cR_totVenta= $functions->formatoValor($cR_moneda, trim($columRes['totventa']));

                                                    $cR_codProg= $privateFunctions->getCodPak_numFile($cR_nFile);
                                                    $cR_codBloq= $privateFunctions->getCodBloq_numFile($cR_nFile);*/


                                                    $cR_estado= trim($columRes->getEstado());
                                                    $imgStatus='';
                                                    $voucherStatus='';
                                                    
                                                    if($cR_estado=='O')
                                                    {
                                                        $imgStatus= '<img src="'.$_layoutParams['ruta_img'].'st_amarillo.png" title="Pendiente de pago" />';
                                                    }
                                                    elseif($cR_estado=='C')
                                                    {
                                                        $imgStatus= '<img src="'.$_layoutParams['ruta_img'].'st_verde.png" title="Pago realizado" />';
                                                        
                                                        if($cR_voucher=='S')
                                                        {
                                                            $voucherStatus='<a href="' . BASE_URL . 'sistema/verPDF/'.$cR_booking.'" target="_blank">
                                                            <img src="'.$_layoutParams['ruta_img'].'pdf.png" alt="edit" width="24" border="0" />
                                                            </a>';
                                                        }
                                                    }
                                                    elseif($cR_estado=='N')
                                                    { 
                                                        $imgStatus= '<img src="'.$_layoutParams['ruta_img'].'st_rojo.png" title="Anulado" />';
                                                    }


                                    ?>
                                    <tr class="odd gradeX">
                                        <td align="center"><?php echo $imgStatus; ?></td>
                                        <td><?php echo $cR_fecha; ?></td>
                                        <td><?php echo $cR_fViaje; ?></td>
                                        <td><?php echo $cR_nFile; ?></td>
                                        <td><?php echo $cR_agencia; ?></td>
                                        <td><?php echo $cR_vendedor; ?></td>
                                        <td><?php echo $cR_pasajero; ?></td>
                                        <td style="color: #FF0000; font-weight: bold;" align="right"><?php echo $cR_moneda.' '.$cR_valorTotal; ?></td>
                                        <td align="center"><?php echo $voucherStatus; ?></td>
                                        <td align="center">
                                        	<a data-toggle="modal" href="#myModal" onClick="abreCartaConfirm('<?php echo $cR_nFile; ?>', '<?php //echo $cR_codProg; ?>', '<?php //echo $cR_codBloq; ?>','<?php echo BASE_URL ?>sistema/reservaBooking');"><img src="<?php echo $_layoutParams['ruta_img']; ?>search.png" width="24" border="0" /></a>
                                        </td>
                                    </tr>
                                  	<?php }
									}
									else
									{
										?>
										<tr>
                                        	<td align="center" colspan="9">
                                            	No se encontraron registros
                                            </td>
                                        </tr>
                                        <?php
									}
								   ?>

                                </tbody>
                            </table>
                        </div>
                    </div>
                    
                    
                    
                    <script>
					$('#btnConsBooking').fadeIn( 100 );
					$('#btnConsBooking').animate({
										'display': 'block'
									});
									
					$('#imgLoading').delay( 10 ).fadeOut( 10 );
					$('#imgLoading').animate({
										'display': 'none'
									});
					
					$('#contenedorBusqueda').fadeIn( 2000 );
					$('#contenedorBusqueda').animate({
										'display': 'block'
									});
					
					</script>
                    <?php } ?>
				</div>
			</div>
            
            


			

		</div> <!-- container -->
	</div> <!--wrap -->
</div> <!-- page-content -->
<script>
$('#btnConsBooking').on('click',function(){
	$(document).skylo('start');

	setTimeout(function(){
		$(document).skylo('set',50);
	},1000);

	setTimeout(function(){
		$(document).skylo('end');
	},1500);
	setTimeout(function(){
		document.getElementById('frmConsRes').submit();
	},2500);
});


function abreCartaConfirm(nFile, codProg, codBloq, php)
{
        $("#ML_divPopup").html('');
        $("#ML_tituloForm").html('Reserva');
	$.post(php, 
	{
		n_file: nFile,
		cod_prog: codProg,
		cod_bloq: codBloq
	}, function(data)
	{   
		$("#modal_dialog").css({"width":"80%"});
                $("#ML_divPopup").html(data);
	});
}
</script>