<div id="page-content">
	<div id='wrap'>
		<div id="page-heading">
        
			<!-- <ol class="breadcrumb">
				<li><a href="index.php">Dashboard</a></li>
				<li>UI Components</li>
				<li class="active">Tabs &amp; Accordions</li>
			</ol> -->

			<h1>Hoteles</h1>
			
		</div>
		
        
        <div class="container">

			

			<div class="row">
				<div class="col-md-12">
					<div class="panel panel-danger">
					  
					  
						<div class="panel panel-info">
                        <div class="panel-heading">
                            <h4>Buscar Hotel</h4>
                        </div>
                        <div class="panel-body">
                            <div class="row">
                            
                            	
                                <div class="col-md-12">
                                	
                            <!--<div class="alert alert-dismissable alert-success">
								<strong>Well done!</strong> You successfully read this important alert message.
								<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
							</div>
							<div class="alert alert-dismissable alert-info">
								<strong>Heads up!</strong> This alert needs your attention, but it's not super important.
								<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
							</div>
							
							<div class="alert alert-dismissable alert-danger">
								<strong>Oh snap!</strong> Change a few things up and try submitting again.
								<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
							</div> -->
                                	<div id="divAlertWarHot" class="alert alert-dismissable alert-warning" style="display:none;">
                                        <strong>Atenci&oacute;n!</strong>
                                        Debe ingresar una <b>Ciudad</b>, <b>Nombre de hotel</b> o seleccionar una <b>Categoria</b>.
                                        <button type="button" class="close" onClick="muestraOculta('divAlertWarHot', '2')">&times;</button>
                                    </div>
                                    <form method="post" id="frmHoteles" action="process/procesoHoteles.php">
                                    <table align="center" cellspacing="5" cellpadding="5">
                                        <tr>
 	                                       <td>Ciudad:</td>
                                           <td>
                                      <input type="text" id="txtCiudad-Hot" name="txtCiudad-Hot" style="width:200px" autocomplete="off"
                                      placeholder="Ingrese ciudad de destino" onkeyup="buscarCiudad(this.value, 'frmHoteles', 'spnCiudad-hoteles', 'txtCiudad-Hot');">
                                    <span id="spnCiudad-hoteles" class="twitter-typeahead" style="position: relative; display: none; direction: ltr;"></span>
                                           </td>
                                           <td>Nombre:</td>
                                           <td>
                                           		<input type="text" id="txtNombre-Hot" name="txtNombre-Hot" style="width:200px" placeholder="Ingrese nombre hotel">
                                           </td>
                                           <td>Categoria:</td>
                                           <td>
                                           		<select name="cmbCategoria" id="cmbCategoria" class="form-control">
                                                <?php
                                                $var_getCategoriasHotel= false; //$privateFunctions->getCategoriasHotel();
												if($var_getCategoriasHotel!=FALSE)
												{
													echo '<option value="0">Todas</option>';
													foreach($var_getCategoriasHotel as $columCatHot)
													{
														$h_nombreCat= trim($columCatHot['nombre']);
												?>
                                                    <option value="<?php echo $h_nombreCat; ?>"><?php echo $h_nombreCat; ?></option>
                                                <?php }
												}?>
                                                </select>
                                           </td>
                                           <td>&nbsp;&nbsp;&nbsp;
                                           <input type="button"  id="btnHoteles" class="btn btn-primary" value="Buscar hoteles">
                                           <img id="imgLoading" src="iconos/loading.gif" style="display:none" width="32" border="0" />
                                           </td>
                                        </tr>
                                    </table>
                                    </form>
                                    
                                </div>
                                
                            </div>
                        </div>
                    </div>	
								
								
								

					  
					</div>
                    
                    
                    <?php
                    if(isset($_SESSION["sess_pH_ciudad"]))
					{
					?>
                     <script>				
					$('#btnHoteles').delay( 10 ).fadeOut( 10 );
					$('#btnHoteles').animate({
										'display': 'none'
									}); 
					$('#imgLoading').fadeIn( 100 );
					$('#imgLoading').animate({
										'display': 'block'
									});
					</script>
                    
                    
                    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                    <h4 class="modal-title" id="tituloForm"></h4>
                                </div>
                                
                                <div class="modal-body" id="divPopupH"></div>
                                
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                                    <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
                                </div>
                            </div><!-- /.modal-content -->
                        </div><!-- /.modal-dialog -->
                    </div><!-- /.modal -->
                    
                    
                    
                    
                    <div class="panel panel-sky" id="contenedorBusqueda" style="display:none">
                        <div class="panel-heading">
                            <h4>Resultado de la busqueda</h4>
                        </div>
                        <div class="panel-body collapse in">
                            <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered datatables" id="example">
                                <thead>
                                    <tr style="background-color:#76c4ed;">
                                        <th>Nombre</th>
                                        <th>Pais</th>
                                        <th>Ciudad</th>
                                        <th>Categor&iacute;a</th>
                                        <th width="100">Modifica</th>
                                        <th width="100">Tipo Hab.</th>
                                    </tr>
                                </thead>
                                <tbody>
                                	
                                    <?php
                                    $var_getHoteles= $privateFunctions->getHoteles($_SESSION["sess_pH_nombre"], $_SESSION["sess_pH_ciudad"], $_SESSION["sess_pH_cat"]);
									if($var_getHoteles!=FALSE)
									{ 
										foreach($var_getHoteles as $columHotel)
										{
											$h_codigoHotel= trim($columHotel['codigo']);
											$h_nombreH= mb_convert_encoding(trim($columHotel['hotel']), "UTF-8", "ISO-8859-1");
											$h_paisH= mb_convert_encoding(trim($columHotel['pais']), "UTF-8", "ISO-8859-1");
											$h_ciudadH= mb_convert_encoding(trim($columHotel['ciudad']), "UTF-8", "ISO-8859-1");
											$h_catH= trim($columHotel['cat']);
									?>
                                       <tr class="odd gradeX">
                                           <td><?php echo $h_nombreH; ?></td>
                                           <td><?php echo $h_paisH; ?></td>
                                           <td><?php echo $h_ciudadH; ?></td>
                                           <td><?php echo $h_catH; ?></td>
                                           <td align="center">
                                           <a data-toggle="modal" href="#myModal" onClick="abrePopupHotel('editHotel.php', 'Editar Hotel', '<?php echo $h_codigoHotel; ?>');">
                                           <img src="iconos/edit.png" width="24" border="0" />
                                           </a></td>
                                           <td align="center">
                                          <a data-toggle="modal" href="#myModal" onClick="abrePopupHotel('editTipoH.php', 'Editar tipo habitaci&oacute;n', '<?php echo $h_codigoHotel; ?>');">
                                           <img src="iconos/camara.png" width="24" border="0" />
                                           </a></td>
                                       </tr>
                                   <?php }
									}
								   ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    
                    
                    <script>
					$('#btnHoteles').fadeIn( 100 );
					$('#btnHoteles').animate({
										'display': 'block'
									});
									
					$('#imgLoading').delay( 10 ).fadeOut( 10 );
					$('#imgLoading').animate({
										'display': 'none'
									});
					
					$('#contenedorBusqueda').fadeIn( 2000 );
					$('#contenedorBusqueda').animate({
										'display': 'block'
									});
					
					</script>
                    <?php }else{ echo '<br><br><br><br><br><br><br><br><br>'; } ?>
				</div>
			</div>
            
            



		</div> <!-- container -->
	</div> <!--wrap -->
</div> <!-- page-content -->