<div id="page-content">
	<div id='wrap'>
		<div id="page-heading">
        
			<!-- <ol class="breadcrumb">
				<li><a href="index.php">Dashboard</a></li>
				<li>UI Components</li>
				<li class="active">Tabs &amp; Accordions</li>
			</ol> -->

			<h1>Im&aacute;genes Clientes</h1>
			
		</div>
		<div class="container">

			

			<div class="row">
				<div class="col-md-12">
					<div class="panel panel-danger">
						
                      
                      	<div class="panel panel-info">
                            <div class="panel-heading">
                                <h4>Seleccione agencia</h4>
                            </div>
                            <div class="panel-body">
                                <div class="row">
                                
                                    <div class="col-md-12">
                                    
                                        <select name="cmbCategoria_lVA" id="cmbCategoria_lVA" style="width:400px" onchange="procesoCargaDiv(this.value, 'lVA_divDetalle', 'detalleLogoVoucherAgen.php')">
                                            <option value="0">Seleccione una agencia</option>
                                           <?php
                                            $var_getAgen= false; //$privateFunctions->getAgencias();
                                            if($var_getAgen!=FALSE)
                                            {
                                                foreach($var_getAgen as $columGetAgen)
                                                {
                                                    $eTH_codTipoH=trim($columGetAgen['id']);
                                                    $eTH_nombreTipoH= mb_convert_encoding(trim($columGetAgen['agencia']), "UTF-8", "ISO-8859-1");
                                            ?>
                                                <option value="<?php echo $eTH_codTipoH; ?>"><?php echo $eTH_nombreTipoH; ?></option>
                                             <?php } 
                                            } ?>
                                        </select>
                                        
                                    </div>
                                    
                                </div>
                            </div>
                        </div>
                      
                      
					  
						<div class="panel panel-info" id="lVA_divDetalle"></div>	
								
								
								

					  
					</div>
				</div>
			</div>
            
            


			

		</div> <!-- container -->
	</div> <!--wrap -->
</div> <!-- page-content -->