<div id="page-content">
	<div id='wrap'>
		<div id="page-heading">
                    <h1>Bienvenido al sistema <?php echo Session::get('sess_nombre'); ?></h1>
		</div>
            
                <div class="container">
                    <div class="row" align="center">
                        <img  src="<?php echo $_layoutParams['ruta_img']; ?>fondo_index.jpg" class="img-responsive">
                    </div>
                </div>
		
	</div> <!--wrap -->
</div> <!-- page-content -->

