<div id="page-content">
    <div id='wrap'>
        <div id="page-heading">
                <ol class="breadcrumb">
                    <li><a href="<?php echo BASE_URL . 'sistema'; ?>">Inicio</a></li>
                    <li class="active">Buscar Servicios</li>
                </ol>


                <h1>Buscar Servicios</h1>
            </div>


        <div class="container">



            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-danger">

                        <div class="panel panel-info">
                            <div class="panel-heading">
                                <h4>Buscar Servicio</h4>
                            </div>
                            <div class="panel-body">
                                <div class="row">


                                    <div class="col-md-12">


                                        <div id="divAlertWarHot" class="alert alert-dismissable alert-warning" style="display:none;">
                                            <strong>Atenci&oacute;n!</strong>
                                            Debe ingresar una <b>Ciudad</b>, <b>Nombre de hotel</b> o seleccionar una <b>Categoria</b>.
                                            <button type="button" class="close" onClick="muestraOculta('divAlertWarHot', '2')">&times;</button>
                                        </div>
                                        <form id="frmServicio_">
                                            
                                            <div>
                                            <a data-toggle="modal" href="#" id="btnCarroServicios_" class="btn btn-success btn-sm" style="width: 88px;" onclick="Servicios.prototype.procesoAddCarro('frmServicio_','<?php echo BASE_URL;?>carro/insertServicio','btnCarroServicios_');">RESERVAR</a>
                                            </div>
                                            
                                        </form>
                                        

                                        

                                    </div>

                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div> 
</div>


