<!-- <div id="page-content" style="min-height: 948px"> -->
<div id="page-content">
    <div id='wrap'>
        <div id="page-heading">
            <ol class="breadcrumb">
                <li><a href="<?php echo BASE_URL . 'sistema'; ?>">Inicio</a></li>
                <li class="active">Carro de compras</li>
            </ol>
            
            <h1>Carro de compras</h1>
        </div>
		
        
        <div class="container">

			

			
            <div class="row">
                <div class="col-lg-12">
                    
                    
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <h4>Detalle</h4>
                        </div>
                        <div class="panel-body">
		  	
                            <div class="tab-content">
                                <div class="tab-pane active" id="domwizard">
                                    <div id="basicwizard" class="form-horizontal">
                                        
                                        
                                        <fieldset title="Paso 1">
                                            <legend style="padding-bottom: 0px; margin-bottom: 0px;"></legend>
                                                
                                                        <div class="table-responsive">

                                                            <form class="frm_paso1"> 
                                                            <table class="table table-bordered table-striped"  style="font-size: 11px;" id="carroTable">
                                                                
                                                               <?php 
                                                               if($this->objCarro){
                                                               
                                                                   ?>
                                                                   <thead>
                                                                    <tr>
                                                                        <th width="5%">Status</th>
                                                                        <th width="25%">Servicio</th>
                                                                        <th width="5%">Habitaci&oacute;n</th>
                                                                        <th width="3%">P.A.</th>
                                                                        <th width="5%">N&deg; hab.</th>
                                                                        <th width="3%">A.</th>
                                                                        <th width="3%">C.</th>
                                                                        <th width="8%">Ciudad</th>
                                                                        <th width="5%">Fecha In</th>
                                                                        <th width="5%">Fecha Out</th>
                                                                        <th width="5%">Vuelo</th>
                                                                        <th width="5%">Total</th>
                                                                        <th width="3%"></th>
                                                                    </tr>
                                                                </thead>
                                                                  <?php
                                                                   $totalCompras = 0;
                                                                   $contProductos = 0;
                                                                   $contServ = 0;
                                                                   $contProg = 0;
                                                                   $contHot = 0;
                                                                   foreach($this->objCarro as $objCar ){
                                                                       $contProductos++;
                                                                       if($objCar->getServicio()=='HTL' && $objCar->getPrograma() == ''){ $contHot++;  }
                                                                       if($objCar->getServicio()=='PRG'){ $contProg++;   }
                                                                       if($objCar->getServicio()!='HTL' && $objCar->getServicio()!='PRG' && $objCar->getPrograma() == ''){$contServ++;   }
                                                                       
                                                                     
                                                               ?>   
                                                                
                                                                        <tbody>
                                                                            <tr>
                                                                                <?php //echo $objCar->getPrograma().'   ';  ?>
                                                                                <th><span class="<?php if($objCar->getStatus() == 'AVAILABLE'){echo 'label label-success';} else{echo 'label label-warning';} ?>"><?php if($objCar->getPrograma() != '' && $objCar->getServicio()== 'HTL'){echo '';} else{ echo $objCar->getStatus(); }?></span></th>
                                                                                <td><?php echo $objCar->getServicio(); ?></td>
                                                                                <td class="text-muted"><?php echo $objCar->getHabitacion() ?></td>
                                                                                <td><?php echo $objCar->getPa() ?></td>
                                                                                <td><?php echo $objCar->getNhab() ?></td>
                                                                                <td><?php echo $objCar->getA() ?></td>
                                                                                <td class="text-muted"><?php echo $objCar->getC() ?></td>
                                                                                <td><?php echo $objCar->getCiudad() ?></td>
                                                                                <td>
                                                                                    <?php if($objCar->getFecha_In()=='0000-00-00') { ?>
                                                                                    
                                                                                        <input type='text' id="txtFechasCarro_<?php echo $contProductos; ?>" name="txtFechasCarro_<?php echo $contProductos; ?>" > 
                                                                                        <script>
                                                                                            $(function()
                                                                                            {
                                                                                            $( "#txtFechasCarro_<?php echo $contProductos; ?>" ).datepicker({
                                                                                                minDate: +1,
                                                                                                defaultDate: "+1w",
                                                                                                changeMonth: true,
                                                                                                numberOfMonths: 1,
                                                                                                monthNames: ['Enero','Febrero','Marzo','Abril','Mayo','Junio',
                                                                                                'Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'],
                                                                                                monthNamesShort: ['Ene','Feb','Mar','Abr','May','Jun',
                                                                                                'Jul','Ago','Sep','Oct','Nov','Dic'],
                                                                                                dayNames: ['Domingo','Lunes','Martes','Mi&eacute;rcoles','Jueves','Viernes','S&aacute;bado'],
                                                                                                dayNamesMin: ['Do','Lu','Ma','Mi','Ju','Vi','S&aacute;'],
                                                                                                dateFormat: 'dd/mm/yy',
                                                                                                firstDay: 1
                                                                                        });});</script>
                                                                                    <?php
                                                                                    
                                                                                    } else { echo Funciones::invertirFecha($objCar->getFecha_in(), '-', '/');} ?><!--  -->
                                                                                
                                                                                </td>
                                                                                <td class="text-muted">
                                                                                    <?php if($objCar->getFecha_out()=='0000-00-00'){echo "";} else {echo Funciones::invertirFecha($objCar->getFecha_out(),'-','/');} ?></td>
                                                                                <td><?php if($objCar->getServicio() == 'TRF'){echo '<input type="text" id="txtCarroVuelo_'.$contProductos.'" name="txtCarroVuelo_'.$contProductos.'">'; }else{echo $objCar->getVuelo();}?></td>
                                                                                <td style="color: #DF5F00; font-weight: bold;"><?php if($objCar->getPrograma() != '' && $objCar->getTotal()== 0){echo '';} else{ echo number_format($objCar->getTotal(), 2); }?></td>                                                                               
                                                                                <td>
                                                                                    <?php
                                                                                    if($objCar->getTotal()!= 0){
                                                                                    ?>
                                                                                    <a data-toggle="modal" href="#myModal" onClick="Carro.prototype.abrePopupCenter('<?php echo BASE_URL ?>carro/mostrarPopUpCarro'
                                                                                                                                                                    , 'Eliminar Producto del Carro', '<?php echo $objCar->getId(); ?>'
                                                                                                                                                                    , '<?php if($objCar->getServicio()=='HTL' && $objCar->getPrograma() == '')
                                                                                                                                                                             { echo $contHot;  } 
                                                                                                                                                                             if($objCar->getServicio()=='PRG'){ echo $contProg;   
                                                                                                                                                                               }
                                                                                                                                                                             if($objCar->getServicio()!='HTL' && $objCar->getServicio()!='PRG' && $objCar->getPrograma() == '')
                                                                                                                                                                             { echo $contServ;   } ?>'
                                                                                                                                                                              ,'<?php echo $objCar->getPrograma();?>'
                                                                                                                                                                              , '<?php echo $objCar->getServicio();?>');">
                                                                                        <img src="<?php echo $_layoutParams['ruta_img']; ?>delete.png" width="24" border="0" />
                                                                                    </a>
                                                                                </td>
                                                                                <?php $totalCompras+=$objCar->getTotal()?>
                                                                            </tr>
                                                                            
                                                                </tbody>
                                                                <?php
                                                                   }
                                                                    }
                                                                   
                                                                   ?>
                                                                            <input type="hidden" id="cantProd" name="cantProd" value="<?php echo $contProductos;?>">
                                                                            <tr>
                                                                                
                                                                                <td colspan="11" align="right"><h5>Total</h5></td>
                                                                                <td colspan="2" style="color: #DF5F00; font-weight: bold;"><h5><?php echo number_format($totalCompras, 2) ?></h5></td>
                                                                                
                                                                            </tr>   
                                                                        </table>
                                                                             <span class="pull-right">
                                                                                <input type="button" class="finish btn-primary btn" id="btnSig_P1" value="Siguiente" />
                                                                            </span>
                                                             <br> 
            
                                                                 <?php
                                                                  
                                                               }
                                                               else{
                                                                ?>  
                                                                        <tr>
                                                                            <td>
                                                                        <center><strong>No se encontraron reservas.</strong></center>
                                                                            </td>
                                                                        </tr>                                                             
                                                                <?php   
                                                               
                                                               }
                           
                                                                ?>
                                                                                                                       
                                                            </table>
                                                            </form>
  
                                                        </div>
                                            
                                        </fieldset>
   
                                        <fieldset title="Paso 2">
                                            
                                            <legend>Detalle de pasajeros</legend>
                                            <form class="frm_paso2">
                                            <div class="table-responsive">
                                      
                                               
                                                <table class="table table-bordered table-striped" style="font-size: 11px; width: 600px;" align="center">
                                                    <tbody> 
                                                    <?php
                                                    $arraySesiones = max(array(Session::get('sess_pBP_cntHab'),  Session::get('sess_sBP_Hab'), Session::get('sess_pBP_cntHab_P'))); 
                                                    
                                                    if($arraySesiones){
                                                    for($i = 1; $i<=$arraySesiones; $i++){  
                                                    ?>
                                                        
                                                        <thead>
                                                        <tr>
                                                            <th width="100">Habitaci&oacute;n <?php echo $i ?></th>
                                                            <th>Nombres</th>
                                                            <th>Apellidos</th>
                                                        </tr>
                                                       </thead>
                                                       <?php
                                                       
                                                       if(Session::get('sess_BP_Adl_'.$i)){
                                                       for($j = 1; $j <=Session::get('sess_BP_Adl_'.$i) ; $j++){                                          
                                                       ?>
                                                        <tr>
                                                            <th>Adulto <?php echo $j;?></th>
                                                            <td><input type="text" class="form-control" id="Carr_txtNombrePas_<?php echo $i.'_'.$j?>" name="Carr_txtNombrePas_<?php echo $i.'_'.$j?>" value=""></td> <?php //if(isset($mL_ini)){ echo $mL_ini; } ?>
                                                            <td><input type="text" class="form-control" id="Carr_txtApellidoPas_<?php echo $i.'_'.$j?>" name="Carr_txtApellidoPas_<?php echo $i.'_'.$j?>" value=""></td><?php //if(isset($mL_ini)){ echo $mL_ini; } ?>
                                                            <?php  
                                                            
                                                            
                                                                
                                                            }
                                                            
                                                            ?>
                                                            
                                                        
                                                        </tr>
                                                       <?php
                                                           }
                                                           
                                                           if(Session::get('sess_BP_Chd_'.$i)){
                                                             for($k = 1; $k <=Session::get('sess_BP_Chd_'.$i) ; $k++){
                                                                 ?>
                                                        <tr>
                                                                 <th>Child <?php echo $k;?></th>
                                                            <td><input type="text" class="form-control" id="Carr_txtNombreCh_<?php echo $i.'_'.$k?>" name="Carr_txtNombreCh_<?php echo $i.'_'.$k?>" value=""></td> <?php //if(isset($mL_ini)){ echo $mL_ini; } ?>
                                                            <td><input type="text" class="form-control" id="Carr_txtApellidoCh_<?php echo $i.'_'.$k?>" name="Carr_txtApellidoCh_<?php echo $i.'_'.$k?>" value=""></td><?php //if(isset($mL_ini)){ echo $mL_ini; } ?>
                                                            
                                                        </tr>         <?php
                                                                 
                                                             }
                                                       }
                                                    }
                                                    ?>
                          
                                                    </tbody>
                                                

                                                </table>
                                                
                                                <table class="table table-bordered table-striped" style="font-size: 11px; width: 600px;" align="center">
                                                    <tr>
                                                        <td>Escriba una nota</td>
                                                        <td><textarea style="height: 150px" id="Carr_textAreaNota" name="Carr_textAreaNota" class="form-control" value="Escriba una nota..."></textarea></td>
                                                        
                                                    </tr>
                                                </table>
                                           <?php
                                                    }
                                                    //Session::destroy('sess_pBP_cntHab');
                                                   
                                           ?>

                                            </div>
                                            
                                            <span class="pull-right">
                                                <input type="button" class="finish btn-default btn" id="btnAtr_P2" value="Atras" />
                                                <input type="button" class="finish btn-primary btn" id="btnSig_P2" value="Siguiente"/>
                                            </span>
                                            <br>
                                            </form>
                                        </fieldset>
    
                                        <fieldset title="Paso 3">
                                            <legend>SOLICITUD DE RESERVA</legend>
                                             <div class="panel panel-info" id="div_paso3">
                                                 
                                            </div>
                                        </fieldset>
                                    </div>
                                </div>


                            </div>

                        </div>
                    </div>
                    
                    
                </div>
            </div>
        </div> <!-- container -->
    </div> <!--wrap -->
</div> <!-- page-content -->

<script type="text/javascript">
$('#btnSig_P1').on('click',function(){
    
    var formData = new FormData($(".frm_paso1")[0]);
        $.ajax({
             type:"POST", 
             url:'<?php echo BASE_URL?>carro/paso2',
             data:formData,
             cache: false,
             contentType: false,
             processData: false,
             beforeSend: function () {
             },
             success:function(data)
             {
                 //alert(data);
                 if(data =="Error"){
                  $('#btnSig_P1').attr("disabled","disabled");
                  $("#btnSig_P1").delay(2000).queue(function(dis)
                 {
                        $("#btnSig_P1").removeAttr("disabled");
                           dis();
                 });   
                  noExito("Ingrese todos los datos"); 
                 }
                 else{
                     
                        //$("#div_paso3").html(data);
                 
                    $('#basicwizard-head-0').removeClass('stepy-active');
                    $('#basicwizard-step-0').css('display', 'none');

                    $('#basicwizard-head-1').addClass('stepy-active');
                    $('#basicwizard-step-1').css('display', 'block');
                 }
             }
         }); 
        
});


$('#btnAtr_P2').on('click',function(){
        
        $('#basicwizard-head-1').removeClass('stepy-active');
        $('#basicwizard-step-1').css('display', 'none');
        
        
        $('#basicwizard-head-0').addClass('stepy-active');
        $('#basicwizard-step-0').css('display', 'block');
        
});
$('#btnSig_P2').on('click',function(){
          
         var formData = new FormData($(".frm_paso2")[0]);
        $.ajax({
             type:"POST", 
             url:'<?php echo BASE_URL?>carro/paso3',
             data:formData,
             cache: false,
             contentType: false,
             processData: false,
             beforeSend: function () {
             },
             success:function(data)
             {
                 if(data =="Error"){
                  $('#btnSig_P2').attr("disabled","disabled");
                  $("#btnSig_P2").delay(2000).queue(function(dis)
                 {
                        $("#btnSig_P2").removeAttr("disabled");
                           dis();
                 });   
                  noExito("Ingrese todos los datos"); 
                 }
                 else{
                     
                        $("#div_paso3").html(data);
                 
                        $('#basicwizard-head-1').removeClass('stepy-active');
                        $('#basicwizard-step-1').css('display', 'none');

                        $('#basicwizard-head-2').addClass('stepy-active');
                        $('#basicwizard-step-2').css('display', 'block');
                 }
             }
         }); 
                
});
</script>