<center><div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  
<?php $publicFotos = ROOT . 'public' . DS . 'img' . DS . 'hoteles'. DS; ?>
  <ol class="carousel-indicators">
    <?php if(file_exists($publicFotos.$this->objFotoEnc)  && $this->objFotoEnc){?> 
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <?php 
    }
    if(file_exists($publicFotos.$this->objFoto1)  && $this->objFoto1){
    ?>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <?php 
    }
    if(file_exists($publicFotos.$this->objFoto2)  && $this->objFoto2){
    ?>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <?php 
    }
    if(file_exists($publicFotos.$this->objFoto3)  && $this->objFoto3){
    ?>
    <li data-target="#myCarousel" data-slide-to="3"></li>
    <?php 
    }
    if(file_exists($publicFotos.$this->objFoto4)  && $this->objFoto4){
    ?>
    
    <li data-target="#myCarousel" data-slide-to="4"></li>
<?php 
    }
    ?>  
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
   
   <?php if(file_exists($publicFotos.$this->objFotoEnc)  && $this->objFotoEnc){?> 
    <div class="item active"> 
      <img src="<?php echo $_layoutParams['ruta_hoteles'].$this->objFotoEnc; ?>" alt="Foto Encabezado">
    </div>  
    <?php
    } 
    if(file_exists($publicFotos.$this->objFoto1)  && $this->objFoto1){?>   
    <div class="item ">
      <img src="<?php echo $_layoutParams['ruta_hoteles'].$this->objFoto1; ?>" alt="Foto 1">
    </div>
     
   <?php }
   if(file_exists($publicFotos.$this->objFoto2)  && $this->objFoto2){?> 
    <div class="item">
      <img src="<?php echo $_layoutParams['ruta_hoteles'].$this->objFoto2; ?>" alt="Foto 2">
    </div>
    
    <?php }
    if(file_exists($publicFotos.$this->objFoto3)  && $this->objFoto3){?>  
    <div class="item">
      <img src="<?php echo $_layoutParams['ruta_hoteles'].$this->objFoto3; ?>" alt="Foto 3">
    </div>
     
    <?php }
    if(file_exists($publicFotos.$this->objFoto4) && $this->objFoto4){?>    
    <div class="item">
      <img src="<?php echo $_layoutParams['ruta_hoteles'].$this->objFoto4; ?>" alt="Foto 4">
    </div>
    <?php }?>   
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" style="background-image: none;" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"><img src="<?php echo $_layoutParams['ruta_img']; ?>leftCircle.png" width="30px" /></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" style="background-image: none;" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"><img src="<?php echo $_layoutParams['ruta_img']; ?>rightCircle.png" width="30px" /></span>
    <span class="sr-only">Next</span>
  </a>
    </div></center>
