<div id="divEdit">
    <script type="text/javascript">
    tinymce.remove();
    tinymce.init({
        selector: "textarea",
        theme: "modern",
        /*width: 300,
        height: 300,*/
        plugins: [
             "advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker",
             "searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking",
             "save table contextmenu directionality emoticons template paste textcolor"
       ],
       menubar : false,
       toolbar: "insertfile undo redo | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | preview | forecolor backcolor fontsizeselect fontselect",
       fontsize_formats: "8pt 10pt 12pt 14pt 18pt 24pt 36pt"
       /*style_formats: [
            {title: 'Bold text', inline: 'b'},
            {title: 'Red text', inline: 'span', styles: {color: '#ff0000'}},
            {title: 'Red header', block: 'h1', styles: {color: '#ff0000'}},
            {title: 'Example 1', inline: 'span', classes: 'example1'},
            {title: 'Example 2', inline: 'span', classes: 'example2'},
            {title: 'Table styles'},
            {title: 'Table row 1', selector: 'tr', classes: 'tablerow1'}
        ]*/
     }); 
    </script>
    
     <form enctype="multipart/form-data" class="frmEditPDF">

    <div class="panel panel-info" id="divEditPDF">
        <div class="panel-heading">
            <h4><b>Programa:</b> <?php echo Session::get('sess_Cod_Prog'); ?></h4>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-12">
                    
                        
                            
                                <div class="col-sm-6">
                                   
                                    <div class="fileinput fileinput-new" data-provides="fileinput">

                                       <?php
                                        $texto_cambiado = str_replace(" ", "_",Session::get('sess_Cod_Prog'));  
                                           $nomArchivo = ROOT. DS .'public'. DS .'pdf'. DS .'upl_'.$texto_cambiado.'.pdf';
                                           
                                           if (file_exists($nomArchivo)) 
                                           {  
                                           ?>
                                        <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 150px; padding-top:10px;">
                                            
                                                    <img src="<?php echo $_layoutParams['ruta_img']; ?>pdf_gran.png" />
                                            
                                            <input id="txtNombreFile" name="txtNombreFile" type="hidden" value="<?php echo 'upl_'.$texto_cambiado.'.pdf'; ?>"/>
                                        </div>
                                        <center>
                                            <label style="cursor:pointer; display: none;">
                                                <input style="margin-top:-1px; vertical-align:middle;" type="checkbox" name="chkEP_flPDF" checked="checked"> Eliminar
                                            </label>
                                            <input type="button"  id="btnEP_CargaPDF" class="btn btn-primary" value="Eliminar Pdf" 
                                            onclick="Programas.prototype.procesoEnviaForm('frmEditPDF', '<?php echo BASE_URL ?>programa/eliminarPdf', 'btnEP_CargaPDF','<?php echo BASE_URL ?>programa/adminProgramas')">
                                        </center>
                                         <?php
                                           }
                                           
                                           else{
                                          ?>
                                        

                                        <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 150px;"></div>
                                        <div>
                                            <span class="btn btn-default btn-file">
                                                <span class="fileinput-new">Seleccionar</span>
                                                <span class="fileinput-exists">Cambiar</span>
                                                <input type="file" name="SpFile" id="SpFile" accept="application/pdf"/>
                                            </span>
                                            <input type="hidden" id="txtFile" name="txtFile" value="<?php echo Session::get('sess_Cod_Prog');?>"/>
                                            <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remover</a>
                                            <input type="button"  id="btnEP_CargaPDF" class="btn btn-primary" value="Subir PDF" 
                                            onclick="Programas.prototype.procesoEnviaForm('frmEditPDF', '<?php echo BASE_URL ?>programa/subirCarPdf', 'btnEP_CargaPDF','<?php echo BASE_URL ?>programa/adminProgramas')">
                                        </div>

                                       <?php
                                       
                                           }
                                       ?>

                                    </div>
                                </div>
                            
                        
                        
                           
                                <div class="col-sm-6">
                                    
                                    <div class="fileinput fileinput-new" data-provides="fileinput">

                                       <?php
                                       
                                        
                                           if (file_exists($this->SP_archivoFoto)) 
                                           {  
                                           ?>
                                        <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 150px; padding-top:10px;">
                                            
                                                    <img src="<?php echo $this->SP_rutaFoto; ?>" />
                                            
                                            <input id="txtNombreFoto" name="txtNombreFoto" type="hidden" value="<?php echo $this->SP_Foto; ?>"/>
                                        </div>
                                        <center>
                                            <label style="cursor:pointer; display: none;">
                                                <input style="margin-top:-1px; vertical-align:middle;" type="checkbox" name="chkEP_flPDF" checked="checked"> Eliminar
                                            </label>
                                            <input type="button"  id="btnEP_CargaFoto" class="btn btn-primary" value="Eliminar Foto" 
                                            onclick="Programas.prototype.procesoEnviaForm('frmEditPDF', '<?php echo BASE_URL ?>programa/eliminarFoto', 'btnEP_CargaFoto','')">
                                        </center>
                                         <?php
                                           }
                                           
                                           else{
                                          ?>
                                        

                                        <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 150px;"></div>
                                        <div>
                                            <span class="btn btn-default btn-file">
                                                <span class="fileinput-new">Seleccionar</span>
                                                <span class="fileinput-exists">Cambiar</span>
                                                <input type="file" name="SpFileFoto" id="SpFileFoto"/>
                                            </span>
                                            <input type="hidden" id="txtFileFoto" name="txtFileFoto" value="<?php echo Session::get('sess_Cod_Prog');?>"/>
                                            <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remover</a>
                                            <input type="button"  id="btnEP_CargaFoto" class="btn btn-primary" value="Subir Foto" 
                                            onclick="Programas.prototype.procesoEnviaForm('frmEditPDF', '<?php echo BASE_URL ?>programa/subirFoto', 'btnEP_CargaFoto','')">
                                        </div>

                                       <?php
                                       
                                           }
                                       ?>

                                    </div>
                                </div>
                            </td>
                        </tr>
                        
                        

                                    </div>
                                </div>
                            </td>
                   
                </div>
            </div>
        </div>
    </div>

</form> 


    <div class="panel panel-info">
        
        <div class="panel-heading">
            <h4>Descripci&oacute;n</h4>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-12">
                    <form method="POST" class="frmDescripcion">
                        <textarea id="descrip" name="areaDescrip" >
                         <?php 
                         if($this->objDescripcion){
                             echo $this->objDescripcion;
                         }
                         else{
                            echo 'Introducir Texto';                             
                         }
                         ?>   
                        </textarea>
                        
                        <br>
                        <center>
                            <input type="button"  id="btnEP_descripcion" class="btn btn-primary" value="Guardar Descripci&oacute;n" 
                            onclick="tinyMCE.triggerSave(); Programas.prototype.procesoEnviaForm('frmDescripcion', '<?php echo BASE_URL ?>programa/subirDescripcion', 'btnEP_descripcion', '')">
                        </center>
                    </form>
                </div>
            </div>
        </div>

    </div>
</div>