<div id="page-content">
    <div id='wrap'>
        <div id="page-heading">
                <ol class="breadcrumb">
                    <li><a href="<?php echo BASE_URL . 'sistema'; ?>">Inicio</a></li>
                    <li class="active">Buscar Servicios</li>
                </ol>

                <h1>Buscar Servicios de <?php if(substr($this->nombreServicio,0,4)== 'A - '){echo substr($this->nombreServicio,3,strlen($this->nombreServicio));  }else{ echo $this->nombreServicio; }?> en <?php echo Session::get('sess_sCH_ciudad') ?></h1>
            </div>   
                <div class="col-md-11" style="margin-left: 70px;">
                    <div class="panel panel-danger">

                        <div class="panel panel-info">
                           
                            
                                <div class="row">

                                  
                             <div class="col-md-11">
                                        
                             <?php 
                             
                             $pest = 0 ;
                             if($this->objBusquedaSer){
                                 
                                 foreach($this->objBusquedaSer as $objServicios){
                                     $pest++;
                             
                             ?>
                            <div class="panel-heading">
                                <h4><?php echo $objServicios->getNombre(); ?></h4>
                            </div>
                             <div class="panel-body">
                            <form class="formSecSer_<?php echo $pest; ?> " action="#" method="post">
                                <div>
                                    
                                    <table width="100%"  style="margin-top: -15px; margin-left: -15px;">
                                         <th width = 15%></th>
                                         <th width = 55%></th>
                                        <tr>
                                            <td rowspan="2" width="250" valign="top">
                                                
                                             <?php 
                                              $texto_cambiado = str_replace(" ", "_",$objServicios->getCodigo());
                                        
                                           $foto = array('jpg', 'jpge','png', 'gif');
                                           $nomArchivo='';
                                           $archivoa = '';
                                           $rutaArchivo='';
                                           
                                           for($i=0; $i<count($foto); $i++){
                                               $rutaArchivo = ROOT. 'public'. DS .'img'. DS .'upl_'.$texto_cambiado.'.'.$foto[$i];
                                               $archivo = 'upl_'.$texto_cambiado.'.'.$foto[$i];
                                               //echo $rutaArchivo;
                                            if(file_exists($rutaArchivo)){  
                                             $nomArchivo = $rutaArchivo;
                                             $archivoa = $archivo;
                                             
                                             }
                                            
                                            
                                           }  
                                           
                                            $fotoa = BASE_URL.'public/img/'.$archivoa;        
                                            
                                      
                                            
                                        
                                             
                                             
                                             ?>   
                                            <img src="<?php echo $fotoa ?>" onerror="src='<?php echo $_layoutParams['ruta_img']; ?>hotel/sinImagen.jpg'" width="120" class="" style="margin-right: 10px;">  
                                            </td>
                                            
                                            
                                        </tr>
                                        <tr>
                                            
                                            <td>
                                                <P ><b style="color:#FF9900;">Descripci&oacute;n:</b></P><p>
                                                   <?php
                                                  //260 caracteres
                                                    if($objServicios->getNotas() == ''){
                                                            foreach($this->objDescrip as $objDes){
                                                                if($objServicios->getCodigo() == $objDes->getCodigo()){
                                                                    
                                                                    if(strlen(html_entity_decode($objDes->getNotas())) <= 200){
                                                                      echo html_entity_decode($objDes->getNotas()); 
                                                                    }
                                                                    else{
                                                                       $primerTexto =  substr(html_entity_decode($objDes->getNotas()),0, 200);
                                                                       $segundoTexto = substr(html_entity_decode($objDes->getNotas()),201, strlen(html_entity_decode($objDes->getNotas())));
                                                                       echo $primerTexto;
                                                                       echo '...';?><strong><a data-toggle="modal" href="#myModal" id="despliegueDescripcion" onclick="despliegue(<?php echo $pest ?>)">Ver mas</a></strong><div style="display:none;" id="descripcion_<?php echo $pest ?>"> <?php echo $primerTexto.$segundoTexto ?></div><?php
                                                                       ?> <script>  </script> <?php
                                                                        
                                                                    }
                                                                }    
                                                            }
                                                        
                                                          } 
                                                          else{
                                                              
                                                              if(strlen($objServicios->getNotas()) <= 200){
                                                              echo $objServicios->getNotas();
                                                              }
                                                              else{
                                                                  $primerTexto =  substr(html_entity_decode($objServicios->getNotas()),0, 200);
                                                                  $segundoTexto = substr(html_entity_decode($objServicios->getNotas()),201, strlen(html_entity_decode($objServicios->getNotas())));
                                                                  echo $primerTexto;
                                                                  echo '...';?><strong><a data-toggle="modal" href="#myModal" id="despliegueDescripcion" onclick="despliegue(<?php echo $pest ?>);">Ver mas</a></strong><div style="display:none;" id="descripcion_<?php echo $pest ?>"> <?php echo $primerTexto.$segundoTexto ?></div><?php
                                                              ?> <?php
                                                                  
                                                              } 
                                                   } ?>
                                                    
                                                </p> 
                                                <!-- <a data-toggle="modal" href="#myModal" id="btnDescServicios" class="btn btn-success btn-sm" style="width: 100px;" onclick="Servicios.prototype.abreDescripcion('<?php echo $objServicios->getCodigo()?>','<?php echo $objServicios->getNotas() ?>','<?php echo BASE_URL;?>servicio/verDescripcion');">Ver Descripci&oacute;n</a> -->  
                                            
                                            </td>
                                            <td valign="top">
                                                <!-- <hr> -->
                                                <table cellpadding="0" cellspacing="0" border="0" class="" style="width: 65%; margin-left: 58px; margin-top: 10px; font-size:12px"> <!-- class="table table-striped table-bordered" -->
                                                   
                                                       
                                                        <tr>
                                                            <?php 
                                                            $compv =  $objServicios->getCompv();
                                                            

                                                            if(($this->objTiposSer=='TRF' || $this->objTiposSer=='EXC') && (Session::get('sess_grupo')=='1' || Session::get('sess_grupo')=='2' ||Session::get('sess_grupo')=='3'))
                                                            {
                                                                                         $compv=Session::get('sess_comag');
                                                                                         $dgcomag=0;
                                                            }
                                                           
                                                            $total_venta= ((($objServicios->getTarifa()*((100-$objServicios->getComcts())/100))/((100-$objServicios->getCompv())/100))*((100-Session::get('sess_comag'))/100)*((100-$this->objDgComag)/100)); ?>
                                                            
                                                            <td style="font-size: 15px; color: #DF5F00; font-weight: bold; padding: 2px; vertical-align: middle;">
                                                               <?php if($objServicios->getMoneda() == 'D'){echo 'USD'.'  '. number_format($total_venta, 2);} else{echo '$'.'  '. number_format($total_venta, 2);}  ?> 
                                                            </td>
                                                            <td width="30%">
                                                             <a data-toggle="modal" href="#" id="btnCarroServicios_<?php echo $pest; ?>" class="btn btn-success btn-sm" style="width: 88px;" onclick="Servicios.prototype.procesoAddCarro('formSecSer_<?php echo $pest; ?>','<?php echo BASE_URL;?>carro/insertServicio','btnCarroServicios_<?php echo $pest; ?>');">RESERVAR</a>
                                                            <input type="hidden" name="tipo_serv_" value ="<?php foreach($objServicios->getTipos()as $objs){ echo $objs->getCodigo();} ?>">
                                                            <input type="hidden" name="nombre_serv_" value ="<?php echo $objServicios->getNombre()  ?>">
                                                            <input type="hidden" name="ope_serv_" value ="<?php echo $objServicios->getOpe()  ?>">
                                                            <input type="hidden" name="codigo_serv_" value ="<?php echo $objServicios->getCodigo()  ?>">
                                                            <input type="hidden" name="totalneto_serv_" value ="<?php echo $objServicios->getTarifa()  ?>">
                                                            <input type="hidden" name="comcts_serv_" value ="<?php echo $objServicios->getComcts()  ?>">
                                                            <input type="hidden" name="compv_serv_" value ="<?php echo $objServicios->getCompv()  ?>">
                                                            <input type="hidden" name="compv_serv_" value ="<?php echo $objServicios->getCompv()  ?>">
                                                            <input type="hidden" name="moneda_serv_" value ="<?php echo $objServicios->getMoneda()  ?>">
                                                            <input type="hidden" name="conv_serv_" value ="<?php echo $objServicios->getConv()  ?>">
                                                            
                                                           
                                                            
                                                            </td>
                                                        <tr>
                                                    

                                                </table>
                                            </td>
                                        </tr>
                                    </table>
                                            
                                    
                                </div>

                            </form>
                                        
                                            
                                            
                                            
                                       

                                   

                                </div>
                                        <br>
                                        <br>
                                       <?php  
                                  }      
                             }
                             else{
                                 ?>
                                        <div class="panel-body">
                                            
                                            <center><strong>No se encontraron registros</strong></center>
                                            
                                        </div>      
                                 <?php 
                                 
                             }
                                        ?>
                            </div>
                                      
                                </div>
                               
                    
                </div>
            </div>
        </div>
    
    
</div>
    
    </div>
<script>
    
    
    function despliegue( pest)
      {
        $("#ML_divPopup").html('');
        $("#ML_tituloForm").html('<strong>Descripci&oacute;n</strong>');
        $("#modal_dialog").css({"width":"50%"});
        $("#modal_dialog").css({"max-height":"70%"});
        //$("#modal_dialog").css({"overflow-y": "auto"});
        $("#descripcion_"+pest).clone().appendTo("#ML_divPopup").css('display','block');
        
      }

</script>


