
<script type="text/javascript" src="http://www.google.com/jsapi?key=AIzaSyByJ-PrjAq7ZDCa8_bCGYB-hzoAJcInrug"></script>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true"></script>
<script>          
function initialize(lat, lon, nombre, id) {
    
        var stockholm = new google.maps.LatLng(lat, lon);
        var parliament = new google.maps.LatLng(lat, lon);
        var marker;
        var map;
        var infowindow = new google.maps.InfoWindow();
        var mapOptions = {
            zoom: 15,
            center: stockholm
        };

        map = new google.maps.Map(document.getElementById('MH_mapa_' + id), mapOptions);

        marker = new google.maps.Marker({
            map: map,
            draggable: true,
            animation: google.maps.Animation.DROP,
            position: parliament
        });


        //google.maps.event.addListener(marker, 'click', toggleBounce);
        // Construct a new InfoWindow.
        infowindow = new google.maps.InfoWindow({
            content: nombre
        });
        // Opens the InfoWindow when marker is clicked.
        marker.addListener('click', function () {
            infowindow.open(map, marker);
        });

    }


    function toggleBounce() {

        if (marker.getAnimation() != null) {
            marker.setAnimation(null);
        } else {
            marker.setAnimation(google.maps.Animation.BOUNCE);
        }
    }
  
                     //google.maps.event.addDomListener(window, 'load',
                     
  </script>
<div id="page-content">
    <div id='wrap'>
        <div id="page-heading">
                <ol class="breadcrumb">
                    <li><a href="<?php echo BASE_URL . 'sistema'; ?>">Inicio</a></li>
                    <li class="active">BUSCAR</li>
                </ol>


            <h1>Hoteles  <?php 
            if(Session::get('sess_pBP_Cagegorias'))
                {
                if(is_numeric(substr(Session::get('sess_pBP_Cagegorias'),0,1))){ 
                    echo 'de '.substr(Session::get('sess_pBP_Cagegorias'),0,1).' Estrellas';
                    
                }
                else{ 
                    echo $this->objCatHot; 
                }    
                } ?> en <?php echo  $this->objCiudadesHotelDet; ?> </h1>
            </div>
                <?php 
                
                $tempCodHTL = '';
                $contPest=0;
                $contPestDet=0;
                $catEstrellas = ''; 
                $detalleHoteles='';
                $html='';
                   
                foreach($this->objGetHoteles as $objHoteles){    
                 if($tempCodHTL != $objHoteles->getCodigoHtl()){
                     
                     
                 $html = file_get_contents(ROOT . 'views' . DS . 'hotel' . DS . 'buscarHoteles' . DS . 'seccionBHoteles.phtml');     
                 $HotelDet=false;                  
                 $contPest++;              
                    foreach($objHoteles->getHotel() as $objHot ){
                        if($objHoteles->getCat() == Session::get('sess_pBP_Cagegorias') || Session::get('sess_pBP_Cagegorias') == ''){
                           if($objHot->getNombre() == Session::get('sess_pBP_nombreHotel') || Session::get('sess_pBP_nombreHotel')==''){ 
                            
                        
                      
                        $catHotel = substr( $objHoteles->getCat(), 0,1);

                                if(is_numeric($catHotel)){
                                
                                        for($i=1; $i<=$catHotel; $i++)
                                        {                 
                                            $catEstrellas .=  '<img src= "' . $_layoutParams['ruta_img'] . 'star_on.png" style="width: 20px; margin-top: -5px;"> ';                                               
                                        }
                                       $catHotel = $catEstrellas; 
                                }
                                else
                                {        
                                 $catHotel = $objHoteles->getCat().' ';   
                                }
                                
                                $arrayServiciosHotel = array(
                                   'restaurant'=>$objHot->getRestaurante(),
                                   'bar'=>$objHot->getBar(),
                                   'cafeteria'=>$objHot->getCafeteria(),
                                   'room_service'=>$objHot->getServHab(),
                                   'acceso_discap'=>$objHot->getDiscapacitados(),
                                   'lavanderia'=>$objHot->getLavanderia(),
                                   'business_center'=>$objHot->getBusiness(),
                                   'internet'=>$objHot->getInterHotel(),
                                   'estacionamiento'=>$objHot->getEstaciona(),
                                   'shopping'=>$objHot->getBoutique(),
                                   'piscina_desc'=>$objHot->getPiscinaDes(),
                                   'spa'=> $objHot->getSpa(),
                                   'gimnasio'=> $objHot->getGym(),
                                   'piscina_cubierta'=> $objHot->getPiscinaCub(),
                                   'tenis'=>$objHot->getTenis(),
                                   'guar_inf'=>$objHot->getGuarderia(),
                                   'salones'=>$objHot->getSalasReu(),
                                   'jardines'=>$objHot->getJardin(),
                                );
                                $imgServHotel = '';
                            
                                foreach( $arrayServiciosHotel as $nombre => $valor)
                                {
                                    if($valor != 0){
                                   $imgServHotel .=  '<img src="'.$_layoutParams['ruta_img'].'hotel/'.$nombre.'.jpg" title="'.$nombre.'">';
                                    }
                                    //echo $_layoutParams['ruta_img'].'/hotel'.$nombre.'.jpg';
                                    
                                }
                                $arrayServiciosHab = array(
                                   'aire_acondicionado'=>$objHot->getAcondicionado(),
                                   'calefaccion'=>$objHot->getCalefaccion(),
                                   'habitacion_no_fum'=>$objHot->getNoFuma(),
                                   'caja_de_seguridad'=>$objHot->getCajaFuerte(),
                                   'minibar'=>$objHot->getMiniBar(),
                                   'tv'=>$objHot->getTv(),
                                   'tv_cable'=>$objHot->getTvCable(),
                                   'telefono'=>$objHot->getTelefono(),
                                   'internet'=>$objHot->getInterHab(),
                                   'secador'=>$objHot->getSecador(),
                                   'barradeseguridad'=>$objHot->getBarraSeg()
                                                        
                                );
                               
                             $imgServHab = '';
                            
                                foreach( $arrayServiciosHab as $nombre => $valor)
                                {                                   
                                    if($valor != 0){
                                   $imgServHab .=  '<img src="'.$_layoutParams['ruta_img'].'hotel/'.$nombre.'.jpg" title="'.$nombre.'">';
                                    }                                   
                                } 
               
                        
                        
                        foreach($this->objGetHoteles as $objTipoH){
                            $contPestDet++;
                            $monedaHot = '';
                            if($objHoteles->getCodigoHtl() ==  $objTipoH->getCodigoHtl()){
                                if($objTipoH->getMoneda() == 'D'){
                                   $monedaHot = 'USD'; 
                                }
                                else{
                                   $monedaHot='CLP'; 
                                }
                              
                              $detalleHoteles.= '<tr class="colorText">'                              
                                    . '<td style="padding: 2px; vertical-align: middle;">'.$objTipoH->getTipoh_nombre().'</td>'
                                    . '<td style="padding: 2px; vertical-align: middle;">'.$objTipoH->getPalimt_nombre().'</td>'
                                    . '<td style="color: #DF5F00; font-weight: bold; padding: 2px; vertical-align: middle;">'.$monedaHot.' '.$objTipoH->getPrecioFinal().'</td>'
                                    . '<td style="padding: 2px; vertical-align: middle;">'
                                    
                                    . '<input type="hidden" name="BH_codHotel"'.$contPest.'" value="'.$objTipoH->getCodigoHtl().'"> '
                                    . '<input type="hidden" name="BH_tipoh"'.$contPest.'" value="'.$objTipoH->getTipoh().'">'
                                    . '<input type="hidden" name="BH_palimt"'.$contPest.'" value="'.$objTipoH->getPalimt().'">'
                                    . '<input type="hidden" name="BH_precioFinal"'.$contPest.'" value="'.$objTipoH->getPrecioFinal().'">'  
                                    . '<a href="#" id="btnCarroEnvio'.$contPestDet.'" onclick=Hoteles.prototype.procesoAddCarro(\'formSecHot'.$contPest.'\',\''.BASE_URL.'carro/insertHotel\',\'btnCarroEnvio'.$contPestDet.'\',\'\') class="btn btn-success btn-sm" style="width: 88px;">'.$objTipoH->getStatus().'</a>'
                                    . '</td>'
                                    . '</tr>';
                                   
                            }
                            
                        }///'.$objHot->getImgEnc().'/'.$objHot->getImgCont().'/'.$objHot->getImgCont2().'/'.$objHot->getImgCont3().'/'.$objHot->getImgCont4().
                
                        $arrayHoteles = array(
                                            'DetalleHotel'=>$detalleHoteles,
                                            'BASE_URL'=> BASE_URL,
                                            'pest'=>$contPest,
                                            'categoria'=>(string)$catHotel,
                                            'hotel'=>$objHot->getNombre(),
                                            'errorFotos'=>$_layoutParams['ruta_img'].'hotel/sinImagen.jpg',
                                            'fotos'=>$_layoutParams["ruta_hoteles"].$objHot->getImgEnc(),
                                            'rutaFotos'=>"Hoteles.prototype.abrePopupFoto('".BASE_URL."hotel/verFotos','<strong>Im&aacute;genes en Hotel ".$objHot->getNombre()."</strong>','".$objHot->getImgEnc()."','".$objHot->getImgCont()."','".$objHot->getImgCont2()."','".$objHot->getImgCont3()."','".$objHot->getImgCont4()."')",
                                            'direccion'=>$objHot->getDirec(),
                                            'nota'=>$objHoteles->getNota(),
                                            'servicios_hotel'=>$imgServHotel,
                                            'servicios_habitacion'=>$imgServHab,
                                            'lat'=>$objHot->getLat(),
                                            'lon'=>$objHot->getLon()                                            
                                            );
                                 $catEstrellas= '';
                                $detalleHoteles= '';
                                foreach($arrayHoteles as $nombre => $valor)
                                { 
                                   $html = str_replace('{' . $nombre . '}', $valor, $html);         
                                }
                               
                              echo $html;
                              ?>  
                 <?php
                           }                                
                    }
                    }
                 }
                 $tempCodHTL = $objHoteles->getCodigoHtl();
                //}
                /*else{
                 ?>
        <center>
                    <table>
                        <tr>
                            <td>
                                    No se encontraron registros;
             
                            </td>
                        </tr>
                    </table>
        </center>
                 <?php
                  break;  
                }*/
                }
                
                
                ?>
        
      
    
       
        
    </div> <!--wrap -->
</div>

<script>

</script>




        
                 

       