<div id="page-content">
	<div id='wrap'>
            <div id="page-heading">
                <ol class="breadcrumb">
                    <li><a href="<?php echo BASE_URL . 'sistema'; ?>">Inicio</a></li>
                    <li class="active">Administraci&oacute;n de Hoteles</li>
                </ol>


                <h1>Hoteles</h1>
            </div>
		
        
        <div class="container">

			

			<div class="row">
				<div class="col-md-12">
					<div class="panel panel-danger">
					  
					  
						<div class="panel panel-info">
                        <div class="panel-heading">
                            <h4>Buscar Hotel</h4>
                        </div>
                        <div class="panel-body">
                            <div class="row">
                            
                            	
                                <div class="col-md-12">
                                	
                            
                                    <div id="divAlertWarHot" class="alert alert-dismissable alert-warning" style="display:none;">
                                        <strong>Atenci&oacute;n!</strong>
                                        Debe ingresar una <b>Ciudad</b> o <b>Nombre de hotel</b>.
                                        <button type="button" class="close" onClick="muestraOculta('divAlertWarHot', '2')">&times;</button>
                                    </div>
                                    
                                    <form method="post" id="frmHoteles" action="<?php echo BASE_URL ?>process/admHoteles">
                                    <table align="center" cellspacing="5" cellpadding="5">
                                        <tr>
 	                                       <td>Ciudad:</td>
                                           <td>
                                    
                                               <!-- <input type="text" id="txtCiudad-Hot" name="txtCiudad-Hot" style="width:200px" autocomplete="off"
                                      placeholder="Ingrese ciudad de destino" onkeyup="buscarCiudad(this.value, 'frmHoteles', 'spnCiudad-hoteles', 'txtCiudad-Hot');">
                                                <span id="spnCiudad-hoteles" class="twitter-typeahead" style="position: relative; display: none; direction: ltr;"></span> -->
                                                
                                                <select name="cmbCiudadDestino_H" id="cmbCiudadDestino_H" class="form-control" >
                                                    <option value="0">Seleccione destino</option>
                                                    <?php 
                                                    if($this->objCiudadesHotel)
                                                    { 
                                                        foreach($this->objCiudadesHotel as $objCiuHot)
                                                        {                                                            
                                                                if(Session::get('sess_pAdm_ciudad')==$objCiuHot->getCiudad()){
                                                                ?>
                                                                    <option value="<?php echo $objCiuHot->getCiudad();?>" selected="selected"> <?php echo $objCiuHot->getCiudad()." (". $objCiuHot->getCodCiudad().")";  ?></option>
                                                                               
                                                                <?php
                                                                                                                      
                                                                }
                                                                else
                                                                {
                                                                ?>
                                                                    <option value="<?php echo $objCiuHot->getCiudad(); ?>"><?php echo $objCiuHot->getCiudad() ." (". $objCiuHot->getCodCiudad().")";
                                                                    ?></option>
                                                                <?php
                                                                }
                                                        }
                                                    }         
                                                    ?>
                                                </select>
                                    
                                           </td>
                                           <td>Nombre:</td>
                                           <td>
                                               <input type="text" id="txtNombre_H" name="txtNombre_H" style="width:200px" value="<?php echo Session::get('sess_pAdm_nombre'); ?>" placeholder="Ingrese nombre hotel">
                                           </td>
                                           <td>Categoria:</td>
                                           <td>
                                                <select name="cmbCategoria_H" id="cmbCategoria_H" class="form-control">
                                                    <option value="0">Todas</option>
                                                    <?php
                                                    if($this->objCategoriaHoteles)
                                                    {
                                                        foreach($this->objCategoriaHoteles as $objCatHot)
                                                        {
                                                            //$asdasd= $this->objCategoriaHoteles->getCategoria();
                                                            $h_objCat = $objCatHot->getCodCat();
                                                            //$h_cat = $this->objCategoriaHoteles->getCodCat();
                                                            
                                                            if(Session::get('sess_pAdm_cat')==$h_objCat)
                                                            {
                                                            ?>
                                                                <option value="<?php echo $objCatHot->getCodCat(); ?>" selected="selected" ><?php echo $objCatHot->getCategoria(); ?></option>
                                                            <?php
                                                            }
                                                            else
                                                            {
                                                            ?>
                                                                <option value="<?php echo $objCatHot->getCodCat(); ?>"><?php echo $objCatHot->getCategoria(); ?></option>
                                                            <?php
                                                            }
                                                        }
                                                    } ?>
                                                </select>
                                           </td>
                                           <td>&nbsp;&nbsp;&nbsp;
                                           <input type="button"  id="btnHoteles" class="btn btn-primary" value="Buscar hoteles">
                                           <img id="imgLoading" src="<?php echo $_layoutParams['ruta_img']; ?>loading.gif" style="display:none" width="32" border="0" />
                                           </td>
                                        </tr>
                                    </table>
                                    </form>
                                    
                                </div>
                                
                            </div>
                        </div>
                    </div>	
								
								
								

					  
					</div>
                    
                    
                    <?php
                    if(Session::get('sess_pAdm_ciudad') || Session::get('sess_pAdm_nombre') || Session::get('sess_pAdm_cat'))
                    {
                    ?>
                    <script>
                        $('#btnHoteles').delay( 10 ).fadeOut( 10 );
                        $('#btnHoteles').animate({
                                                    'display': 'none'
                                                }); 
                        $('#imgLoading').fadeIn( 100 );
                        $('#imgLoading').animate({
                                                    'display': 'block'
                                                });
                    </script>
                                 
                    
                    
                    
                    
                    <div class="panel panel-sky" id="contenedorBusqueda" style="display:none">
                        <div class="panel-heading">
                            <h4>Resultado de la busqueda</h4>
                        </div>
                        <div class="panel-body collapse in">
                            <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered datatables" id="example">
                                <thead>
                                    <tr style="background-color:#76c4ed;">
                                        <th>Nombre</th>
                                        <th>Pais</th>
                                        <th>Ciudad</th>
                                        <th>Categor&iacute;a</th>
                                        <th width="100">Modifica</th>
                                    </tr>
                                </thead>
                                <tbody>
                                	
                                    <?php
                                    if($this->getHoteles)
                                    {
                                        foreach($this->getHoteles as $columHotel)
                                        {
                                            $h_codigoHotel= trim($columHotel['codigo']);
                                            $h_nombreH= trim($columHotel['hotel']);
                                            $h_paisH= trim($columHotel['pais']);
                                            $h_ciudadH= trim($columHotel['ciudad']);
                                            $h_catH= trim($columHotel['cat']);
									?>
                                       <tr class="odd gradeX">
                                           <td><?php echo $h_nombreH; ?></td>
                                           <td><?php echo $h_paisH; ?></td>
                                           <td><?php echo $h_ciudadH; ?></td>
                                           <td><?php echo $h_catH; ?></td>
                                             <td align="center">
                                           <a data-toggle="modal" href="#myModal" onClick="Hoteles.prototype.abrePopupCenter('<?php echo BASE_URL ?>hotel/editHotel', 'Editar Hotel', '<?php echo $h_codigoHotel; ?>');">
                                           <img src="<?php echo $_layoutParams['ruta_img']; ?>edit.png" width="24" border="0" />
                                           </a></td>
                                          
                                       </tr>
                                   <?php }
									}
								   ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    
                    
                    <script>
					$('#btnHoteles').fadeIn( 100 );
					$('#btnHoteles').animate({
										'display': 'block'
									});
									
					$('#imgLoading').delay( 10 ).fadeOut( 10 );
					$('#imgLoading').animate({
										'display': 'none'
									});
					
					$('#contenedorBusqueda').fadeIn( 2000 );
					$('#contenedorBusqueda').animate({
										'display': 'block'
									});
					
					</script>
                    <?php }else{ echo '<br><br><br><br><br><br><br><br><br>'; } ?>
				</div>
			</div>
            
            

<script>
$('#btnHoteles').on('click',function()
{
    $("#btnHoteles").attr('disabled', 'disabled');
    /*if($('#cmbCiudadDestino_H').val()==0 || $('#txtNombre_H').val()=='')
    {
        $('#divAlertWarHot').fadeIn( 1500 );
        $('#divAlertWarHot').animate({
                'display': 'block'
        });
        
        $("#btnHoteles").delay(2000).queue(function(dis)
        {
            $("#btnHoteles").removeAttr("disabled");
            dis();
        });
    }*/
    //else
    //{
        $(document).skylo('start');

        setTimeout(function(){
                $(document).skylo('set',50);
        },1000);

        setTimeout(function(){
                $(document).skylo('end');
        },1500);
        setTimeout(function(){
                document.getElementById('frmHoteles').submit();
        },2500);
        
        $("#btnHoteles").delay(5000).queue(function(dis)
        {
            $("#btnHoteles").removeAttr("disabled");
            dis();
        });
    //}
    
});
</script>
		</div> <!-- container -->
	</div> <!--wrap -->
</div> <!-- page-content -->